language: generic
os:
  - linux
dist: trusty
sudo: false
env:
  global:
    - DEVKITARM=$HOME/devkitARM
addons:
  apt:
    sources:
      - llvm-toolchain-trusty
    packages:
      - gcc-multilib
      - clang-5.0
      - clang-format-5.0
      - cmake
cache:
  apt: true
before_install:
  - cmake -DCLANG_FORMAT=/usr/bin/clang-format-5.0 -P scripts/format.cmake
install:
  - cd $HOME
  - travis_retry wget http://download.sourceforge.net/devkitpro/devkitARM_r46-x86_64-linux.tar.bz2
  - tar xf devkitARM*.tar.bz2

  - travis_retry git clone https://github.com/pret/agbcc.git
  - mkdir "$TRAVIS_BUILD_DIR/tools"
  - cd agbcc && ./build.sh && ./install.sh $TRAVIS_BUILD_DIR

  - mkdir .tmp
  - curl -L https://github.com/ninja-build/ninja/releases/download/v1.7.2/ninja-linux.zip -o .tmp/ninja-linux.zip
  - unzip .tmp/ninja-linux.zip -d .tmp
  - export PATH=$PWD/.tmp:$PATH
  - export CC=/usr/bin/clang-5.0
  - export CXX=/usr/bin/clang++-5.0
script:
  - cd $TRAVIS_BUILD_DIR
  - mkdir build
  - cd build
  - cmake .. -DDEVKITARM=$DEVKITARM -DAGBCC=$TRAVIS_BUILD_DIR/tools/agbcc -GNinja
  - ninja compare
