cmake_minimum_required(VERSION 3.21)

project(beybladevforce LANGUAGES C ASM)

if(CMAKE_BINARY_DIR STREQUAL CMAKE_SOURCE_DIR)
    message(FATAL_ERROR "Building in-source is not supported. Remove CMakeCache.txt and use a separate build directory.")
endif()

set(CMAKE_EXPORT_COMPILE_COMMANDS ON)

add_executable(rom
    asm/arm1.s
    asm/arm2.s
    asm/audio0.s
    asm/audio1.s
    asm/audio2.s
    asm/crt0.s
    asm/data1.s
    asm/data10.s
    asm/data11.s
    asm/data12.s
    asm/data3.s
    asm/data4.s
    asm/data5.s
    asm/data6.s
    asm/data7.s
    asm/data8.s
    asm/data9.s
    asm/dataA.s
    asm/dataB.s
    asm/dataC.s
    asm/dump/8040d18/8040d18-creditsFrontendHandler.s
    asm/dump/8040d18/8041078.s
    asm/dump/8040d18/80410b4-displayFrontendLevel.s
    asm/dump/8040d18/8041188.s
    asm/dump/8040d18/8041288.s
    asm/dump/8040d18/8041324.s
    asm/dump/8040d18/8041344.s
    asm/dump/8040d18/8041364.s
    asm/dump/8040d18/8041390.s
    asm/dump/8040d18/80413fc.s
    asm/dump/8040d18/8041ea0-teletypeDefaultUserCodeHandler.s
    asm/dump/8040d18/80420c4.s
    asm/dump/8040d18/804257c.s
    asm/dump/8040d18/80427e4-collectionListFrontendHandler.s
    asm/dump/8040d18/80431e8.s
    asm/dump/8040d18/804323c-profile.s
    asm/dump/8040d18/8043370.s
    asm/dump/8040d18/80434ec.s
    asm/dump/8040d18/8043558.s
    asm/dump/8040d18/8043604.s
    asm/dump/8040d18/80436b0.s
    asm/dump/8040d18/8043720.s
    asm/dump/8040d18/804374c.s
    asm/dump/8040d18/804385c.s
    asm/dump/8040d18/80438cc.s
    asm/dump/8040d18/804393c.s
    asm/dump/8040d18/8043960.s
    asm/dump/8040d18/8043970.s
    asm/dump/8040d18/80439a0.s
    asm/dump/8040d18/80439f4.s
    asm/dump/8040d18/8043a0c.s
    asm/dump/8040d18/8043a58.s
    asm/dump/8040d18/8043aa0.s
    asm/dump/8040d18/8043cf8.s
    asm/dump/8040d18/8043d84.s
    asm/dump/8040d18/8043db8.s
    asm/dump/8040d18/8043f40.s
    asm/dump/8040d18/8044054.s
    asm/dump/8040d18/804423c.s
    asm/dump/8040d18/8044314.s
    asm/dump/8040d18/804444c.s
    asm/dump/8040d18/80448f4.s
    asm/dump/8040d18/8044c48.s
    asm/dump/8040d18/8044ed4.s
    asm/dump/8040d18/8045160.s
    asm/dump/8040d18/80453d8.s
    asm/dump/8040d18/804541c.s
    asm/dump/8040d18/8045638.s
    asm/dump/8040d18/804566c.s
    asm/dump/8040d18/804568c.s
    asm/dump/8040d18/8045848.s
    asm/dump/8040d18/8045a7c.s
    asm/dump/8040d18/8045cb4.s
    asm/dump/8040d18/80461d8.s
    asm/dump/8040d18/8046424.s
    asm/dump/8040d18/8046468.s
    asm/dump/8040d18/80464c0.s
    asm/dump/8040d18/8046500.s
    asm/dump/8040d18/8046814.s
    asm/dump/8040d18/8046a0c.s
    asm/dump/8040d18/8046b94.s
    asm/dump/8040d18/8046cc4.s
    asm/dump/8040d18/8046f2c-initBBCollectionSprite.s
    asm/dump/8040d18/804703c.s
    asm/dump/8040d18/8047080.s
    asm/dump/8040d18/80470c8.s
    asm/dump/8040d18/804712c.s
    asm/dump/8040d18/8047494.s
    asm/dump/8040d18/80475e0-selectBladeFrontendHandler.s
    asm/dump/8040d18/8047e5c.s
    asm/dump/8040d18/80480ec.s
    asm/dump/8040d18/8048310.s
    asm/dump/8040d18/804868c.s
    asm/dump/8040d18/8048a74.s
    asm/dump/8040d18/8048ae8.s
    asm/dump/8040d18/8048d8c.s
    asm/dump/8040d18/8048f80.s
    asm/dump/8040d18/8048fb4.s
    asm/dump/8040d18/8048fc4-nullsub_38.s
    asm/dump/8040d18/8048fc8-nullsub_33.s
    asm/dump/8040d18/8048fcc.s
    asm/dump/8040d18/8048fd4.s
    asm/dump/8040d18/8048fe4.s
    asm/dump/8040d18/8048ffc.s
    asm/dump/8040d18/8049018.s
    asm/dump/8040d18/804903c.s
    asm/dump/8040d18/8049074.s
    asm/dump/8040d18/80490cc.s
    asm/dump/8040d18/80490f8.s
    asm/dump/8040d18/804915c.s
    asm/dump/8040d18/8049168.s
    asm/dump/8040d18/8049178.s
    asm/dump/8040d18/80491c4.s
    asm/dump/8040d18/80491e0.s
    asm/dump/8040d18/8049210.s
    asm/dump/8040d18/8049234.s
    asm/dump/8040d18/8049240.s
    asm/dump/8040d18/804924c.s
    asm/dump/8040d18/8049258.s
    asm/dump/8040d18/8049264.s
    asm/dump/8040d18/8049320-StoreFunction.s
    asm/dump/8040d18/8049330.s
    asm/dump/8040d18/8049344.s
    asm/dump/8040d18/80493c8.s
    asm/dump/8040d18/8049458.s
    asm/dump/8040d18/80495c4.s
    asm/dump/8040d18/804967c.s
    asm/dump/8040d18/8049ce8.s
    asm/dump/8040d18/8049de0.s
    asm/dump/8040d18/8049f58.s
    asm/dump/8040d18/8049f9c.s
    asm/dump/8040d18/8049ff8.s
    asm/dump/8040d18/804a0e0.s
    asm/dump/8040d18/804a110.s
    asm/dump/8040d18/804a1e4.s
    asm/dump/8040d18/804a234.s
    asm/dump/8040d18/804a26c.s
    asm/dump/8040d18/804a280.s
    asm/dump/8040d18/804a2f0.s
    asm/dump/8040d18/804a300.s
    asm/dump/8040d18/804a310.s
    asm/dump/8040d18/804a320.s
    asm/dump/8040d18/804a330.s
    asm/dump/8040d18/804a33c.s
    asm/dump/8040d18/804a348.s
    asm/dump/8040d18/804a358-StoreLevelVar14.s
    asm/dump/8040d18/804a364.s
    asm/dump/8040d18/804a378.s
    asm/dump/804a388-tutorial/804a388-initTutorialManagement.s
    asm/dump/804a388-tutorial/804a488-turorial_804A488.s
    asm/dump/804a388-tutorial/804a504.s
    asm/dump/804a388-tutorial/804a51c.s
    asm/dump/804a388-tutorial/804a550.s
    asm/dump/804a388-tutorial/804a72c.s
    asm/dump/804a388-tutorial/804a744.s
    asm/dump/804a388-tutorial/804a7e8.s
    asm/dump/804a388-tutorial/804a7f8.s
    asm/dump/804a388-tutorial/804a820-nullsub_32.s
    asm/dump/804a388-tutorial/804a824.s
    asm/dump/804a388-tutorial/804a830.s
    asm/dump/804a388-tutorial/804a838-newSpriteTrail.s
    asm/dump/804a388-tutorial/804a908.s
    asm/dump/804a388-tutorial/804ab50.s
    asm/dump/804a388-tutorial/804ab60-nullsub_39.s
    asm/dump/804a388-tutorial/804ab64.s
    asm/dump/804a388-tutorial/804ab88.s
    asm/dump/804a388-tutorial/804abd0.s
    asm/dump/804a388-tutorial/804abd8.s
    asm/dump/804a388-tutorial/804abe4.s
    asm/dump/804a388-tutorial/804abfc.s
    asm/dump/804a388-tutorial/804acf0.s
    asm/dump/804a388-tutorial/804ad28.s
    asm/dump/804a388-tutorial/804ad44.s
    asm/dump/804a388-tutorial/804ad50.s
    asm/dump/804a388-tutorial/804ad60.s
    asm/dump/804a388-tutorial/804ad74.s
    asm/dump/804a388-tutorial/804ae30-nullsub_40.s
    asm/dump/804a388-tutorial/804ae34.s
    asm/dump/804a388-tutorial/804ae8c.s
    asm/dump/804a388-tutorial/804aecc.s
    asm/dump/804a388-tutorial/804af04.s
    asm/dump/804a388-tutorial/804af5c.s
    asm/dump/804a388-tutorial/804af9c.s
    asm/dump/804a388-tutorial/804afb8.s
    asm/dump/804a388-tutorial/804afd4.s
    asm/dump/804a388-tutorial/804b00c.s
    asm/dump/804a388-tutorial/804b044.s
    asm/dump/804a388-tutorial/804b060.s
    asm/dump/804a388-tutorial/804b07c-initRider.s
    asm/dump/804a388-tutorial/804b2cc-processRiderMetadata.s
    asm/dump/804a388-tutorial/804b4a4.s
    asm/dump/804a388-tutorial/804b4fc.s
    asm/dump/804a388-tutorial/804b5c0.s
    asm/dump/804a388-tutorial/804b620-nullsub_1.s
    asm/dump/804a388-tutorial/804b624.s
    asm/dump/804a388-tutorial/804b754.s
    asm/dump/804a388-tutorial/804b7fc.s
    asm/dump/804a388-tutorial/804b8f0.s
    asm/dump/804a388-tutorial/804bbf0-renderRider.s
    asm/dump/804a388-tutorial/804bedc-allocFXSprite.s
    asm/dump/804a388-tutorial/804bf3c.s
    asm/dump/804a388-tutorial/804c098.s
    asm/dump/804a388-tutorial/804c0c0.s
    asm/dump/804a388-tutorial/804c0ec.s
    asm/dump/804a388-tutorial/804c118.s
    asm/dump/804a388-tutorial/804c154-nullsub_2.s
    asm/dump/804a388-tutorial/804c158-nullsub_3.s
    asm/dump/804a388-tutorial/804c15c-nullsub_4.s
    asm/dump/804a388-tutorial/804c160-newProjectileSystem.s
    asm/dump/804a388-tutorial/804c208.s
    asm/dump/804a388-tutorial/804c34c.s
    asm/dump/804a388-tutorial/804c354.s
    asm/dump/804a388-tutorial/804c35c.s
    asm/dump/804a388-tutorial/804c3d4.s
    asm/dump/804a388-tutorial/804c464.s
    asm/dump/804a388-tutorial/804c484.s
    asm/dump/804a388-tutorial/804c4b4-s_rider_804C4B4.s
    asm/dump/804a388-tutorial/804c870.s
    asm/dump/804a388-tutorial/804c888.s
    asm/dump/804a388-tutorial/804c8c0.s
    asm/dump/804a388-tutorial/804c8f0-RiderAI_804C8F0.s
    asm/dump/804a388-tutorial/804cb08.s
    asm/dump/804a388-tutorial/804cef4.s
    asm/dump/804a388-tutorial/804d048.s
    asm/dump/804a388-tutorial/804d104.s
    asm/dump/804a388-tutorial/804d110.s
    asm/dump/804a388-tutorial/804d710.s
    asm/dump/804a388-tutorial/804d754.s
    asm/dump/804a388-tutorial/804d8d8.s
    asm/dump/804a388-tutorial/804da44-nullsub_5.s
    asm/dump/804a388-tutorial/804da48.s
    asm/dump/804a388-tutorial/804daa0.s
    asm/dump/804a388-tutorial/804db94-rider_vs_rider_collision_804DB94.s
    asm/dump/804a388-tutorial/804ddf8.s
    asm/dump/804a388-tutorial/804df88.s
    asm/dump/804a388-tutorial/804dff4.s
    asm/dump/804a388-tutorial/804e090.s
    asm/dump/804a388-tutorial/804e124.s
    asm/dump/804a388-tutorial/804e154.s
    asm/dump/804a388-tutorial/804e1dc.s
    asm/dump/804a388-tutorial/804e1fc.s
    asm/dump/804a388-tutorial/804e20c.s
    asm/dump/804a388-tutorial/804e224.s
    asm/dump/804a388-tutorial/804e258.s
    asm/dump/804a388-tutorial/804e2a4.s
    asm/dump/804a388-tutorial/804e328.s
    asm/dump/804a388-tutorial/804e358.s
    asm/dump/804a388-tutorial/804e3b0.s
    asm/dump/804a388-tutorial/804e3e4-convert3DCoordsto2DCoords.s
    asm/dump/804a388-tutorial/804e400-SetRiderFlag.s
    asm/dump/804a388-tutorial/804e40c-UnsetRiderFlag.s
    asm/dump/804a388-tutorial/804e418-RiderHasFlag.s
    asm/dump/804a388-tutorial/804e42c-RiderHasSomeFlags.s
    asm/dump/804a388-tutorial/804e440.s
    asm/dump/804a388-tutorial/804e454.s
    asm/dump/804a388-tutorial/804e468-allocateParticleSystem.s
    asm/dump/804a388-tutorial/804e530.s
    asm/dump/804a388-tutorial/804e560.s
    asm/dump/804a388-tutorial/804e57c.s
    asm/dump/804a388-tutorial/804e584.s
    asm/dump/804a388-tutorial/804e594.s
    asm/dump/804a388-tutorial/804e6a4.s
    asm/dump/804a388-tutorial/804e7d4.s
    asm/dump/804a388-tutorial/804e910.s
    asm/dump/804a388-tutorial/804ea88.s
    asm/dump/804a388-tutorial/804ebe8.s
    asm/dump/804a388-tutorial/804ec14-LoadHUD.s
    asm/dump/804a388-tutorial/804ee2c.s
    asm/dump/804a388-tutorial/804ee54.s
    asm/dump/804a388-tutorial/804f05c.s
    asm/dump/804a388-tutorial/804f2a0.s
    asm/dump/804a388-tutorial/804f37c.s
    asm/dump/804a388-tutorial/804f478.s
    asm/dump/804a388-tutorial/804f794.s
    asm/dump/804a388-tutorial/804f800.s
    asm/dump/804a388-tutorial/804f824.s
    asm/dump/804a388-tutorial/804f84c.s
    asm/dump/804a388-tutorial/804f878.s
    asm/dump/804a388-tutorial/804f9b4.s
    asm/dump/804a388-tutorial/804fa40.s
    asm/dump/804a388-tutorial/804fad4.s
    asm/dump/804a388-tutorial/804fb6c.s
    asm/dump/804a388-tutorial/804fc00.s
    asm/dump/804a388-tutorial/804fcac-getItem.s
    asm/dump/804a388-tutorial/804fd64.s
    asm/dump/804a388-tutorial/804fe14.s
    asm/dump/804a388-tutorial/804fe30.s
    asm/dump/804a388-tutorial/804fe50.s
    asm/dump/804a388-tutorial/804fe9c.s
    asm/dump/804a388-tutorial/804fee8.s
    asm/dump/804a388-tutorial/804ff5c.s
    asm/dump/804a388-tutorial/804ff88.s
    asm/dump/804a388-tutorial/804ffd4.s
    asm/dump/804a388-tutorial/805000c.s
    asm/dump/804a388-tutorial/8050050.s
    asm/dump/804a388-tutorial/8050114.s
    asm/dump/804a388-tutorial/8050184.s
    asm/dump/804a388-tutorial/80501a8.s
    asm/dump/804a388-tutorial/80501c8.s
    asm/dump/804a388-tutorial/80501f8.s
    asm/dump/804a388-tutorial/805024c.s
    asm/dump/804a388-tutorial/8050284.s
    asm/dump/804a388-tutorial/80502a4.s
    asm/dump/804a388-tutorial/805032c.s
    asm/dump/804a388-tutorial/8050334.s
    asm/dump/804a388-tutorial/805033c.s
    asm/dump/804a388-tutorial/8050340.s
    asm/dump/804a388-tutorial/805034c.s
    asm/dump/804a388-tutorial/8050364.s
    asm/dump/804a388-tutorial/8050384.s
    asm/dump/804a388-tutorial/8050394-newMotionGroup.s
    asm/dump/804a388-tutorial/805041c.s
    asm/dump/804a388-tutorial/80504e4.s
    asm/dump/804a388-tutorial/805052c.s
    asm/dump/804a388-tutorial/8050574.s
    asm/dump/804a388-tutorial/8050578.s
    asm/dump/804a388-tutorial/8050584.s
    asm/dump/804a388-tutorial/80505a4-mainLoop.s
    asm/dump/804a388-tutorial/8050694-onVBlank.s
    asm/dump/804a388-tutorial/80506b0-nullsub_37.s
    asm/dump/804a388-tutorial/80506b4-onTimer1Overflow.s
    asm/dump/804a388-tutorial/80506c0.s
    asm/dump/804a388-tutorial/80506f4-newLayerManagement.s
    asm/dump/804a388-tutorial/8050894.s
    asm/dump/804a388-tutorial/80508a4.s
    asm/dump/804a388-tutorial/80508cc.s
    asm/dump/804a388-tutorial/8050a50.s
    asm/dump/804a388-tutorial/8050a78-nullsub_41.s
    asm/dump/804a388-tutorial/8050a7c-newIconMenu.s
    asm/dump/804a388-tutorial/8050c18.s
    asm/dump/804a388-tutorial/8050df8.s
    asm/dump/804a388-tutorial/8050e80.s
    asm/dump/804a388-tutorial/8050f0c.s
    asm/dump/804a388-tutorial/8050f98.s
    asm/dump/804a388-tutorial/8050fc8.s
    asm/dump/804a388-tutorial/8050fe8.s
    asm/dump/804a388-tutorial/8050fec.s
    asm/dump/804a388-tutorial/8050ff0.s
    asm/dump/804a388-tutorial/805100c.s
    asm/dump/804a388-tutorial/8051028.s
    asm/dump/804a388-tutorial/805106c-InitCurrentGameState.s
    asm/dump/804a388-tutorial/80510fc.s
    asm/dump/804a388-tutorial/80512ac.s
    asm/dump/804a388-tutorial/805137c.s
    asm/dump/804a388-tutorial/80513ac.s
    asm/dump/804a388-tutorial/8051488.s
    asm/dump/804a388-tutorial/8051558.s
    asm/dump/804a388-tutorial/80515a4.s
    asm/dump/804a388-tutorial/80515e0.s
    asm/dump/804a388-tutorial/8051618.s
    asm/dump/804a388-tutorial/805162c.s
    asm/dump/804a388-tutorial/8051640.s
    asm/dump/804a388-tutorial/8051654-getSomeLevelID.s
    asm/dump/804a388-tutorial/8051688.s
    asm/dump/804a388-tutorial/8051694.s
    asm/dump/804a388-tutorial/80516b0.s
    asm/dump/804a388-tutorial/80516c0.s
    asm/dump/804a388-tutorial/80516d4.s
    asm/dump/804a388-tutorial/80516e0.s
    asm/dump/804a388-tutorial/80516f8-getLevelDescription2.s
    asm/dump/804a388-tutorial/8051710-getLevelDescription.s
    asm/dump/804a388-tutorial/8051720.s
    asm/dump/804a388-tutorial/8051734.s
    asm/dump/804a388-tutorial/8051744.s
    asm/dump/804a388-tutorial/805176c.s
    asm/dump/804a388-tutorial/8051780.s
    asm/dump/804a388-tutorial/8051798.s
    asm/dump/804a388-tutorial/80517ac-GetLevelDescriptionNo.s
    asm/dump/804a388-tutorial/80517e8.s
    asm/dump/804a388-tutorial/8051804.s
    asm/dump/804a388-tutorial/8051820.s
    asm/dump/804a388-tutorial/805185c.s
    asm/dump/804a388-tutorial/8051868.s
    asm/dump/804a388-tutorial/805187c.s
    asm/dump/804a388-tutorial/80518c8.s
    asm/dump/804a388-tutorial/80518f0.s
    asm/dump/804a388-tutorial/8051918-gameLoop.s
    asm/dump/804a388-tutorial/80520f4.s
    asm/dump/804a388-tutorial/8052140.s
    asm/dump/804a388-tutorial/8052180.s
    asm/dump/804a388-tutorial/80522d4.s
    asm/dump/804a388-tutorial/8052514.s
    asm/dump/804a388-tutorial/8052534.s
    asm/dump/804a388-tutorial/805253c.s
    asm/dump/804a388-tutorial/8052588.s
    asm/dump/804a388-tutorial/80526c8.s
    asm/dump/804a388-tutorial/805295c.s
    asm/dump/804a388-tutorial/8052978.s
    asm/dump/804a388-tutorial/8052a74.s
    asm/dump/804a388-tutorial/8052ab8.s
    asm/dump/804a388-tutorial/8052afc-nullsub_43.s
    asm/dump/804a388-tutorial/8052b00-nullsub_44.s
    asm/dump/804a388-tutorial/8052b04-nullsub_45.s
    asm/dump/804a388-tutorial/8052b08.s
    asm/dump/804a388-tutorial/8052b24.s
    asm/dump/804a388-tutorial/80532b8-initGame.s
    asm/dump/804a388-tutorial/8053374-initGameLoop.s
    asm/dump/804a388-tutorial/8053600-initRiders.s
    asm/dump/804a388-tutorial/80538c0.s
    asm/dump/804a388-tutorial/8053920.s
    asm/dump/804a388-tutorial/8053954.s
    asm/dump/804a388-tutorial/8053978-loadLevelGeometry.s
    asm/dump/804a388-tutorial/8053990-getLevelMetadata.s
    asm/dump/804a388-tutorial/80539a0-GetStruct4.s
    asm/dump/804a388-tutorial/80539c4.s
    asm/dump/804a388-tutorial/80539e8.s
    asm/dump/804a388-tutorial/8053b04-initCollisionData.s
    asm/dump/804a388-tutorial/8053b94.s
    asm/dump/804a388-tutorial/8053cb4-closeGame.s
    asm/dump/804a388-tutorial/8053d58-initGameloop2.s
    asm/dump/804a388-tutorial/8053e18.s
    asm/dump/804a388-tutorial/8053ef8.s
    asm/dump/804a388-tutorial/8053f0c.s
    asm/dump/804a388-tutorial/80540c8.s
    asm/dump/804a388-tutorial/80540e0-SetRiderGlobal.s
    asm/dump/804a388-tutorial/80540ec-initEventListeners.s
    asm/dump/804a388-tutorial/805420c-deallocEventListeners.s
    asm/dump/804a388-tutorial/8054248-processMetadata_6.s
    asm/dump/804a388-tutorial/8054278.s
    asm/dump/804a388-tutorial/80542a8-handleEventListeners.s
    asm/dump/804a388-tutorial/8054388-processMetadata_default.s
    asm/dump/804a388-tutorial/80543a4-nullsub_42.s
    asm/dump/804a388-tutorial/80543a8-processMetadata_1.s
    asm/dump/804a388-tutorial/805444c-processMetadata_2.s
    asm/dump/804a388-tutorial/80544bc-processMetadata_3.s
    asm/dump/804a388-tutorial/805450c-processMetadata_4.s
    asm/dump/804a388-tutorial/80545b0-processMetadata_5.s
    asm/dump/804a388-tutorial/8054684-processMetadata_8.s
    asm/dump/804a388-tutorial/80546a4-processMetadata_9.s
    asm/dump/804a388-tutorial/80546c8-processMetadata_A.s
    asm/dump/804a388-tutorial/80546e8-processMetadata_C.s
    asm/dump/804a388-tutorial/805470c-processMetadata_D.s
    asm/dump/804a388-tutorial/8054714-processMetadata_E.s
    asm/dump/804a388-tutorial/8054738-nullsub_14.s
    asm/dump/804a388-tutorial/805473c-processMetadata_10.s
    asm/dump/804a388-tutorial/8054764-nullsub_15.s
    asm/dump/804a388-tutorial/8054768-initLevelEnvironmentActors.s
    asm/dump/804a388-tutorial/8054c9c-renderEnvironmentActors.s
    asm/dump/804a388-tutorial/8054eb4-updateEnvirenmentActors.s
    asm/dump/804a388-tutorial/8054fe0.s
    asm/dump/804a388-tutorial/80550b8.s
    asm/dump/804a388-tutorial/80550f4-initProjectileSystem.s
    asm/dump/804a388-tutorial/8055274.s
    asm/dump/804a388-tutorial/8055288.s
    asm/dump/804a388-tutorial/805529c.s
    asm/dump/804a388-tutorial/8055340.s
    asm/dump/804a388-tutorial/80555f4.s
    asm/dump/804a388-tutorial/8055624.s
    asm/dump/804a388-tutorial/805565c.s
    asm/dump/804a388-tutorial/8055674.s
    asm/dump/804a388-tutorial/805568c.s
    asm/dump/804a388-tutorial/80556c4.s
    asm/dump/804a388-tutorial/80556dc.s
    asm/dump/804a388-tutorial/80556f4.s
    asm/dump/804a388-tutorial/8055734.s
    asm/dump/804a388-tutorial/805582c.s
    asm/dump/804a388-tutorial/805589c.s
    asm/dump/804a388-tutorial/80558b8.s
    asm/dump/804a388-tutorial/80558d0.s
    asm/dump/804a388-tutorial/80558e8.s
    asm/dump/804a388-tutorial/8055914.s
    asm/dump/804a388-tutorial/805599c.s
    asm/dump/804a388-tutorial/8055b64.s
    asm/dump/804a388-tutorial/8055b7c.s
    asm/dump/804a388-tutorial/8055ba0.s
    asm/dump/804a388-tutorial/8055bb0.s
    asm/dump/804a388-tutorial/8055bc0.s
    asm/dump/804a388-tutorial/8055c04.s
    asm/dump/804a388-tutorial/8055c18.s
    asm/dump/804a388-tutorial/8055c30.s
    asm/dump/804a388-tutorial/8055c4c.s
    asm/dump/804a388-tutorial/8055c58-getDecompressorData.s
    asm/dump/804a388-tutorial/8055ca0.s
    asm/dump/804a388-tutorial/8055cb8.s
    asm/dump/804a388-tutorial/8055cfc-def_94_0_8055CFC.s
    asm/dump/804a388-tutorial/8055d64.s
    asm/dump/804a388-tutorial/8055f04.s
    asm/dump/804a388-tutorial/8055f2c-def_94_8_collision_8055F2C.s
    asm/dump/804a388-tutorial/8056154-nullsub_6.s
    asm/dump/804a388-tutorial/8056158.s
    asm/dump/804a388-tutorial/805616c-def_94_4_AddWithBoundingAreaMessage.s
    asm/dump/804a388-tutorial/80561a0.s
    asm/dump/804a388-tutorial/80561ec.s
    asm/dump/804a388-tutorial/8056610.s
    asm/dump/804a388-tutorial/80567e4.s
    asm/dump/804a388-tutorial/8056910.s
    asm/dump/804a388-tutorial/8056adc.s
    asm/dump/804a388-tutorial/8056b54.s
    asm/dump/804a388-tutorial/8056c08-_return_false.s
    asm/dump/804a388-tutorial/8056c0c.s
    asm/dump/804a388-tutorial/8056c80.s
    asm/dump/804a388-tutorial/8056cfc.s
    asm/dump/804a388-tutorial/8056d44-initCollectables.s
    asm/dump/804a388-tutorial/8056e2c.s
    asm/dump/804a388-tutorial/8056ec0.s
    asm/dump/804a388-tutorial/8056f7c.s
    asm/dump/804a388-tutorial/8056fac.s
    asm/dump/804a388-tutorial/8057038-nullsub_7.s
    asm/dump/804a388-tutorial/805703c.s
    asm/dump/804a388-tutorial/8057048.s
    asm/dump/804a388-tutorial/8057068.s
    asm/dump/804a388-tutorial/8057094.s
    asm/dump/804a388-tutorial/80570c0.s
    asm/dump/804a388-tutorial/80570d4.s
    asm/dump/804a388-tutorial/8057104.s
    asm/dump/804a388-tutorial/8057158.s
    asm/dump/804a388-tutorial/8057164.s
    asm/dump/804a388-tutorial/80571d0.s
    asm/dump/804a388-tutorial/80571e4-GetTalkingHead.s
    asm/dump/804a388-tutorial/80571f8-emptyBeybladeActorData.s
    asm/dump/804a388-tutorial/8057228-deallocBeybladeActorData.s
    asm/dump/804a388-tutorial/8057258-getBeyBladeActorDataForIndex.s
    asm/dump/804a388-tutorial/8057338-getBeybladeData0.s
    asm/dump/804a388-tutorial/8057348-getBeybladeActorData.s
    asm/dump/804a388-tutorial/8057360-allocateBeyBladeActorPalette.s
    asm/dump/804a388-tutorial/8057398-allocateBeybladeObjectPalettes.s
    asm/dump/804a388-tutorial/80573c8.s
    asm/dump/804a388-tutorial/80573dc.s
    asm/dump/804a388-tutorial/80573fc.s
    asm/dump/804a388-tutorial/805741c.s
    asm/dump/804a388-tutorial/805743c.s
    asm/dump/804a388-tutorial/805745c.s
    asm/dump/804a388-tutorial/805747c.s
    asm/dump/804a388-tutorial/805749c.s
    asm/dump/804a388-tutorial/80574a8-initBattery.s
    asm/dump/804a388-tutorial/80574d0.s
    asm/dump/804a388-tutorial/8057568.s
    asm/dump/804a388-tutorial/80575f4-initAiManagement.s
    asm/dump/804a388-tutorial/80576ec.s
    asm/dump/804a388-tutorial/80577a0-deallocateAiManagement.s
    asm/dump/804a388-tutorial/80577d4-fn_aiStubFunc.s
    asm/dump/804a388-tutorial/80577d8.s
    asm/dump/804a388-tutorial/8057878.s
    asm/dump/80578e0/80578e0.s
    asm/dump/80578e0/805791c.s
    asm/dump/80578e0/8057930.s
    asm/dump/80578e0/8057944.s
    asm/dump/80578e0/8057984.s
    asm/dump/80578e0/80579a8-InitStuff_SetDispStat.s
    asm/dump/80578e0/80579f4-EnableInterrupt.s
    asm/dump/80578e0/8057a08-DisableInterrupt.s
    asm/dump/80578e0/8057a1c.s
    asm/dump/80578e0/8057a44-loadPalette.s
    asm/dump/80578e0/8057a60-loadPalette2.s
    asm/dump/80578e0/8057a7c.s
    asm/dump/80578e0/8057b30.s
    asm/dump/80578e0/8057b38-nullsub_31.s
    asm/dump/80578e0/8057b3c-nullsub_8.s
    asm/dump/80578e0/8057b40-nullsub_9.s
    asm/dump/80578e0/8057b44-nullsub_10.s
    asm/dump/80578e0/8057b48-nullsub_25.s
    asm/dump/80578e0/8057b4c-nullsub_26.s
    asm/dump/80578e0/8057b50-nullsub_27.s
    asm/dump/80578e0/8057b54.s
    asm/dump/80578e0/8057b64.s
    asm/dump/80578e0/8057b74-nullsub_28.s
    asm/dump/80578e0/8057b78-nullsub_29.s
    asm/dump/80578e0/8057b7c-nullsub_30.s
    asm/dump/8057b80-debug/8057b80-assert.s
    asm/dump/8057b80-debug/8057c1c-nullsub_17.s
    asm/dump/8057b80-debug/8057c20-nullsub_46.s
    asm/dump/8057b80-debug/8057c24-nullsub_18.s
    asm/dump/8057b80-debug/8057c28-nullsub_19.s
    asm/dump/8057b80-debug/8057c2c-nullsub_20.s
    asm/dump/8057b80-debug/8057c30-printf_2.s
    asm/dump/8057b80-debug/8057c38-printf.s
    asm/dump/8057b80-debug/8057c40.s
    asm/dump/8057b80-debug/8057c4c-GetVCount.s
    asm/dump/8057b80-debug/8057c58-actor_8057C58.s
    asm/dump/8057b80-debug/8057d88-renderActor.s
    asm/dump/8057b80-debug/8057fac.s
    asm/dump/8057b80-debug/8057fdc.s
    asm/dump/8057b80-debug/8058038.s
    asm/dump/8057b80-debug/8058068.s
    asm/dump/8057b80-debug/80580b4-GetSpriteSheetStructA.s
    asm/dump/8057b80-debug/80580c0-actor_80580C0.s
    asm/dump/8057b80-debug/8058110.s
    asm/dump/8057b80-debug/8058144.s
    asm/dump/8057b80-debug/805816c.s
    asm/dump/8057b80-debug/80581b8.s
    asm/dump/8057b80-debug/8058220-ActorSetFrameSequence.s
    asm/dump/8057b80-debug/80582d0.s
    asm/dump/8057b80-debug/805832c.s
    asm/dump/8057b80-debug/8058390.s
    asm/dump/8057b80-debug/80583dc-ActorSetFrame.s
    asm/dump/8057b80-debug/8058478.s
    asm/dump/8057b80-debug/80584b8.s
    asm/dump/8057b80-debug/80585c8.s
    asm/dump/8057b80-debug/80585e8.s
    asm/dump/8057b80-debug/80585f0-actor_80585F0.s
    asm/dump/8057b80-debug/80585f8-actor_80585F8.s
    asm/dump/8057b80-debug/8058614-rider_8058614.s
    asm/dump/8057b80-debug/8058624-ActorSetSpriteOffset.s
    asm/dump/8057b80-debug/8058630.s
    asm/dump/8057b80-debug/8058638-actor_8058638.s
    asm/dump/8057b80-debug/8058754.s
    asm/dump/8057b80-debug/8058778-renderActor2.s
    asm/dump/8057b80-debug/8058784.s
    asm/dump/8057b80-debug/8058794.s
    asm/dump/8057b80-debug/8058838.s
    asm/dump/8057b80-debug/80588a8.s
    asm/dump/8057b80-debug/80588dc.s
    asm/dump/8057b80-debug/8058914-nullsub_49.s
    asm/dump/8057b80-debug/8058918-nullsub_50.s
    asm/dump/8057b80-debug/805891c-nullsub_11.s
    asm/dump/8057b80-debug/8058920-nullsub_51.s
    asm/dump/8057b80-debug/8058924.s
    asm/dump/8057b80-debug/805893c.s
    asm/dump/8057b80-debug/8058968.s
    asm/dump/8057b80-debug/8058c74.s
    asm/dump/8057b80-debug/8058e18.s
    asm/dump/8057b80-debug/8058ef4.s
    asm/dump/8057b80-debug/8058f60.s
    asm/dump/8057b80-debug/8059058-allocateActorMotionModifiers.s
    asm/dump/8057b80-debug/8059110.s
    asm/dump/8057b80-debug/8059184-nullsub_24.s
    asm/dump/8057b80-debug/8059188.s
    asm/dump/8057b80-debug/8059284.s
    asm/dump/8057b80-debug/8059310.s
    asm/dump/8057b80-debug/8059404.s
    asm/dump/8057b80-debug/80594fc.s
    asm/dump/8057b80-debug/80595fc.s
    asm/dump/8057b80-debug/80596ac.s
    asm/dump/8057b80-debug/8059904.s
    asm/dump/8057b80-debug/8059934.s
    asm/dump/8057b80-debug/8059994.s
    asm/dump/8057b80-debug/8059a68-SetBGOffset.s
    asm/dump/8057b80-debug/8059b00.s
    asm/dump/8057b80-debug/8059c18.s
    asm/dump/8057b80-debug/8059cb4.s
    asm/dump/8057b80-debug/8059cc8.s
    asm/dump/8057b80-debug/8059cf0.s
    asm/dump/8057b80-debug/8059d04-ToggleLayerVisibility.s
    asm/dump/8057b80-debug/8059db8.s
    asm/dump/8057b80-debug/8059ddc.s
    asm/dump/8057b80-debug/8059e5c.s
    asm/dump/8057b80-debug/8059ebc.s
    asm/dump/8057b80-debug/8059f20.s
    asm/dump/8057b80-debug/8059fa0.s
    asm/dump/8057b80-debug/8059fb8.s
    asm/dump/8057b80-debug/8059fd0.s
    asm/dump/8057b80-debug/8059ff8.s
    asm/dump/8057b80-debug/805a00c.s
    asm/dump/8057b80-debug/805a0dc.s
    asm/dump/8057b80-debug/805a148.s
    asm/dump/8057b80-debug/805a1dc.s
    asm/dump/8057b80-debug/805a290.s
    asm/dump/8057b80-debug/805a2dc.s
    asm/dump/8057b80-debug/805a350-initBlockVariables.s
    asm/dump/8057b80-debug/805a3a8-fastAllocate.s
    asm/dump/8057b80-debug/805a420-slowAllocate.s
    asm/dump/8057b80-debug/805a498-deallocateBlock.s
    asm/dump/8057b80-debug/805a53c.s
    asm/dump/8057b80-debug/805a5e4-getValidAllocatedBlock.s
    asm/dump/8057b80-debug/805a614-printTotalWramUsage.s
    asm/dump/8057b80-debug/805a664-printTotalExramUsage.s
    asm/dump/8057b80-debug/805a6b0-nullsub_34.s
    asm/dump/8057b80-debug/805a6b4-nullsub_35.s
    asm/dump/8057b80-debug/805a6b8-updateKeyState.s
    asm/dump/8057b80-debug/805a86c-initKeyState.s
    asm/dump/8057b80-debug/805a914.s
    asm/dump/8057b80-debug/805a930.s
    asm/dump/8057b80-debug/805a93c.s
    asm/dump/8057b80-debug/805a984.s
    asm/dump/8057b80-debug/805aa50-initKeyRecording.s
    asm/dump/8057b80-debug/805aab4.s
    asm/dump/8057b80-debug/805aad4.s
    asm/dump/8057b80-debug/805aae0.s
    asm/dump/8057b80-debug/805aaec.s
    asm/dump/8057b80-debug/805ab38.s
    asm/dump/8057b80-debug/805ab44.s
    asm/dump/8057b80-debug/805ab58.s
    asm/dump/8057b80-debug/805ab6c.s
    asm/dump/8057b80-debug/805abb4.s
    asm/dump/8057b80-debug/805abc0.s
    asm/dump/8057b80-debug/805ac28.s
    asm/dump/8057b80-debug/805ac5c.s
    asm/dump/8057b80-debug/805ac68.s
    asm/dump/8057b80-debug/805ac80.s
    asm/dump/8057b80-debug/805ad24.s
    asm/dump/8057b80-debug/805ad9c.s
    asm/dump/8057b80-debug/805add4-allocateMenuItems.s
    asm/dump/8057b80-debug/805afb8-nullsub_48.s
    asm/dump/8057b80-debug/805afbc.s
    asm/dump/8057b80-debug/805b050.s
    asm/dump/8057b80-debug/805b0bc.s
    asm/dump/8057b80-debug/805b0f0.s
    asm/dump/8057b80-debug/805b13c.s
    asm/dump/8057b80-debug/805b1a0.s
    asm/dump/8057b80-debug/805b1e0.s
    asm/dump/8057b80-debug/805b210.s
    asm/dump/8057b80-debug/805b240.s
    asm/dump/8057b80-debug/805b244.s
    asm/dump/8057b80-debug/805b260.s
    asm/dump/8057b80-debug/805b268.s
    asm/dump/8057b80-debug/805b26c.s
    asm/dump/8057b80-debug/805b270.s
    asm/dump/8057b80-debug/805b280.s
    asm/dump/8057b80-debug/805b394.s
    asm/dump/8057b80-debug/805b3dc.s
    asm/dump/8057b80-debug/805b41c.s
    asm/dump/8057b80-debug/805b668.s
    asm/dump/8057b80-debug/805b700.s
    asm/dump/8057b80-debug/805b7f0.s
    asm/dump/8057b80-debug/805b800.s
    asm/dump/8057b80-debug/805b8c4-getLevelGeometryAddresses.s
    asm/dump/8057b80-debug/805b938-newCollisionDataRam.s
    asm/dump/8057b80-debug/805ba3c.s
    asm/dump/8057b80-debug/805ba54-StoreMetadataAddr.s
    asm/dump/8057b80-debug/805ba60-GetLineMetaData.s
    asm/dump/8057b80-debug/805ba7c.s
    asm/dump/8057b80-debug/805bac0.s
    asm/dump/8057b80-debug/805bad8-getLineMetaAtIndex.s
    asm/dump/8057b80-debug/805bafc.s
    asm/dump/8057b80-debug/805bb2c-getLineMetaObjectBytype.s
    asm/dump/8057b80-debug/805bb5c-getLineMetaobjectByTypeAndId.s
    asm/dump/8057b80-debug/805bb9c-initQuadTree.s
    asm/dump/8057b80-debug/805bbc8-allocQuadTree.s
    asm/dump/8057b80-debug/805bdbc.s
    asm/dump/8057b80-debug/805bf18.s
    asm/dump/8057b80-debug/805bfc4-deallocateQuadTree.s
    asm/dump/8057b80-debug/805bfe8-allocateDynamicBoundingAreas.s
    asm/dump/8057b80-debug/805c040-initQuadTreeNode.s
    asm/dump/8057b80-debug/805c308-GetQuadTreeNodeForPos.s
    asm/dump/8057b80-debug/805c3bc.s
    asm/dump/8057b80-debug/805c444.s
    asm/dump/8057b80-debug/805c48c-actor_805C48C.s
    asm/dump/8057b80-debug/805c9a4.s
    asm/dump/8057b80-debug/805ceb8.s
    asm/dump/8057b80-debug/805d400-call_rider_94_8.s
    asm/dump/8057b80-debug/805d430.s
    asm/dump/8057b80-debug/805d488.s
    asm/dump/8057b80-debug/805d548.s
    asm/dump/8057b80-debug/805d610.s
    asm/dump/8057b80-debug/805d650.s
    asm/dump/8057b80-debug/805db6c.s
    asm/dump/8057b80-debug/805db80-GetSplineAtIndex.s
    asm/dump/8057b80-debug/805dbac-GetPointAtIndex.s
    asm/dump/8057b80-debug/805dbc0-GetPointAtSplineIndex.s
    asm/dump/8057b80-debug/805dbf0.s
    asm/dump/8057b80-debug/805dcd4-GetSplineLineAtIndex.s
    asm/dump/8057b80-debug/805dcfc.s
    asm/dump/8057b80-debug/805dd18.s
    asm/dump/8057b80-debug/805df04.s
    asm/dump/8057b80-debug/805dfd4.s
    asm/dump/8057b80-debug/805e068.s
    asm/dump/8057b80-debug/805e0d8.s
    asm/dump/8057b80-debug/805e18c.s
    asm/dump/8057b80-debug/805e320.s
    asm/dump/8057b80-debug/805e474.s
    asm/dump/8057b80-debug/805e50c.s
    asm/dump/8057b80-debug/805e514.s
    asm/dump/8057b80-debug/805e528.s
    asm/dump/8057b80-debug/805e648.s
    asm/dump/8057b80-debug/805e77c.s
    asm/dump/8057b80-debug/805e7c0.s
    asm/dump/8057b80-debug/805e804.s
    asm/dump/8057b80-debug/805e83c-GetLineIndexOfType.s
    asm/dump/8057b80-debug/805e878.s
    asm/dump/8057b80-debug/805e8a0.s
    asm/dump/8057b80-debug/805e8b0.s
    asm/dump/8057b80-debug/805e8d8.s
    asm/dump/8057b80-debug/805eadc.s
    asm/dump/8057b80-debug/805eb00.s
    asm/dump/8057b80-debug/805ebc8-nullsub_12.s
    asm/dump/8057b80-debug/805ebcc.s
    asm/dump/8057b80-debug/805ed60.s
    asm/dump/8057b80-debug/805ee78.s
    asm/dump/8057b80-debug/805eea4.s
    asm/dump/8057b80-debug/805eee0.s
    asm/dump/8057b80-debug/805eefc.s
    asm/dump/8057b80-debug/805ef18.s
    asm/dump/8057b80-debug/805ef9c-allocateRenderCode.s
    asm/dump/8057b80-debug/805f0b4.s
    asm/dump/8057b80-debug/805f1e4.s
    asm/dump/8057b80-debug/805f1ec.s
    asm/dump/8057b80-debug/805f1f4.s
    asm/dump/8057b80-debug/805f218.s
    asm/dump/8057b80-debug/805f23c.s
    asm/dump/8057b80-debug/805f258.s
    asm/dump/8057b80-debug/805f27c.s
    asm/dump/8057b80-debug/805f378.s
    asm/dump/8057b80-debug/805f3a8.s
    asm/dump/8057b80-debug/805f3d8.s
    asm/dump/8057b80-debug/805f400.s
    asm/dump/8057b80-debug/805f47c.s
    asm/dump/8057b80-debug/805f730.s
    asm/dump/8057b80-debug/805f784.s
    asm/dump/8057b80-debug/805f7fc.s
    asm/dump/8057b80-debug/805f848.s
    asm/dump/8057b80-debug/805f864.s
    asm/dump/8057b80-debug/805f884.s
    asm/dump/8057b80-debug/805f8c0.s
    asm/dump/8057b80-debug/805f8d4.s
    asm/dump/8057b80-debug/805f8ec.s
    asm/dump/8057b80-debug/805f8f8.s
    asm/dump/8057b80-debug/805f910.s
    asm/dump/8057b80-debug/805f98c.s
    asm/dump/8057b80-debug/805f9ac.s
    asm/dump/8057b80-debug/805f9d4-newPolyTable.s
    asm/dump/8057b80-debug/805fa4c.s
    asm/dump/8057b80-debug/805fa68.s
    asm/dump/8057b80-debug/805fa8c.s
    asm/dump/8057b80-debug/805fae8.s
    asm/dump/8057b80-debug/805fb60.s
    asm/dump/8057b80-debug/805fbe0.s
    asm/dump/8057b80-debug/805fcc8.s
    asm/dump/8057b80-debug/805fcec.s
    asm/dump/8057b80-debug/805fd80.s
    asm/dump/8057b80-debug/805fe04.s
    asm/dump/8057b80-debug/805fe68.s
    asm/dump/8057b80-debug/805fed0-initMultiPlayer.s
    asm/dump/8057b80-debug/805ffe4.s
    asm/dump/8057b80-debug/806003c-nullsub_47.s
    asm/dump/8057b80-debug/8060040.s
    asm/dump/8057b80-debug/8060070.s
    asm/dump/8057b80-debug/806008c.s
    asm/dump/8057b80-debug/80600a8-isMultiplayer.s
    asm/dump/8057b80-debug/80600b4.s
    asm/dump/8057b80-debug/806014c.s
    asm/dump/8057b80-debug/80603e8.s
    asm/dump/8057b80-debug/8060404.s
    asm/dump/8057b80-debug/8060434.s
    asm/dump/8057b80-debug/8060454-onSerialCommunication.s
    asm/dump/8057b80-debug/80604d4.s
    asm/dump/8057b80-debug/8060520-SpriteVRamFree.s
    asm/dump/8057b80-debug/8060790.s
    asm/dump/8057b80-debug/8060808-freeSpriteVramLocation.s
    asm/dump/8057b80-debug/80608cc.s
    asm/dump/8057b80-debug/8060934.s
    asm/dump/8057b80-debug/80609c4.s
    asm/dump/8057b80-debug/80609e0-allocSprite.s
    asm/dump/8057b80-debug/8060a60.s
    asm/dump/8057b80-debug/8060a94.s
    asm/dump/8057b80-debug/8060b0c.s
    asm/dump/8057b80-debug/8060b38.s
    asm/dump/8057b80-debug/8060b68-LoadSpriteSheet.s
    asm/dump/8057b80-debug/8060c1c.s
    asm/dump/8057b80-debug/8060cdc.s
    asm/dump/8057b80-debug/8060d98-resizeSpriteBlock.s
    asm/dump/8057b80-debug/8060e8c.s
    asm/dump/8057b80-debug/8060f64.s
    asm/dump/8057b80-debug/806100c.s
    asm/dump/8057b80-debug/8061030.s
    asm/dump/8057b80-debug/8061078.s
    asm/dump/8057b80-debug/80610ec.s
    asm/dump/8057b80-debug/8061110.s
    asm/dump/8057b80-debug/8061130.s
    asm/dump/8057b80-debug/806114c.s
    asm/dump/8057b80-debug/8061158.s
    asm/dump/8057b80-debug/8061160.s
    asm/dump/8057b80-debug/8061168.s
    asm/dump/8057b80-debug/8061184.s
    asm/dump/8057b80-debug/8061190-allocFont.s
    asm/dump/8057b80-debug/80611ec.s
    asm/dump/8057b80-debug/80611f4.s
    asm/dump/8057b80-debug/80611fc.s
    asm/dump/8057b80-debug/8061204.s
    asm/dump/8057b80-debug/8061228.s
    asm/dump/8057b80-debug/806123c.s
    asm/dump/8057b80-debug/80614b0.s
    asm/dump/8057b80-debug/80614bc-showString.s
    asm/dump/8057b80-debug/8061660.s
    asm/dump/8057b80-debug/8061684.s
    asm/dump/8057b80-debug/8061824.s
    asm/dump/8057b80-debug/8061844.s
    asm/dump/8057b80-debug/806185c.s
    asm/dump/8057b80-debug/8061880.s
    asm/dump/8057b80-debug/80618d0-showNumber.s
    asm/dump/8057b80-debug/8061980-showNumber_2.s
    asm/dump/8057b80-debug/80619a4.s
    asm/dump/8057b80-debug/8061a18-printTime.s
    asm/dump/8057b80-debug/8061ae8.s
    asm/dump/8057b80-debug/8061ba0.s
    asm/dump/8057b80-debug/8061c24.s
    asm/dump/8057b80-debug/8061c48.s
    asm/dump/8057b80-debug/8061c6c.s
    asm/dump/8057b80-debug/8061c90.s
    asm/dump/8057b80-debug/8061cb4.s
    asm/dump/8057b80-debug/8061d54.s
    asm/dump/8057b80-debug/8061d68.s
    asm/dump/8057b80-debug/8061e08.s
    asm/dump/8057b80-debug/8061e44.s
    asm/dump/8057b80-debug/8061e58.s
    asm/dump/8057b80-debug/8061e90.s
    asm/dump/8057b80-debug/8061e94.s
    asm/dump/8057b80-debug/8061e9c.s
    asm/dump/8057b80-debug/8061f3c.s
    asm/dump/8057b80-debug/80622d0.s
    asm/dump/8057b80-debug/80622e8.s
    asm/dump/8057b80-debug/8062318.s
    asm/dump/8057b80-debug/8062e70-allocateActorHeaps.s
    asm/dump/8057b80-debug/8062efc.s
    asm/dump/8057b80-debug/8062fa8.s
    asm/dump/8057b80-debug/8062fe0.s
    asm/dump/8057b80-debug/8063058.s
    asm/dump/8057b80-debug/806306c.s
    asm/dump/8057b80-debug/80630f4.s
    asm/dump/8057b80-debug/8063128.s
    asm/dump/8057b80-debug/806315c.s
    asm/dump/8057b80-debug/8063190.s
    asm/dump/8057b80-debug/80631b0.s
    asm/dump/8057b80-debug/80631ec.s
    asm/dump/8057b80-debug/8063220.s
    asm/dump/8057b80-debug/8063454.s
    asm/dump/8057b80-debug/8063544.s
    asm/dump/8057b80-debug/8063640.s
    asm/dump/8057b80-debug/8063704.s
    asm/dump/8057b80-debug/80637cc-deallocate_80637CC.s
    asm/dump/8057b80-debug/80637e4.s
    asm/dump/8057b80-debug/8063830.s
    asm/dump/8057b80-debug/8063a50.s
    asm/dump/8057b80-debug/8063a68.s
    asm/dump/8057b80-debug/8063a7c.s
    asm/dump/8057b80-debug/8063a88.s
    asm/dump/8057b80-debug/8063a94.s
    asm/dump/8057b80-debug/8063aa0-getLanguage.s
    asm/dump/8057b80-debug/8063ab4.s
    asm/dump/8057b80-debug/8063ad8.s
    asm/dump/8057b80-debug/8063b44.s
    asm/dump/8057b80-debug/8063ba8.s
    asm/dump/8057b80-debug/8063cd0.s
    asm/dump/8057b80-debug/8063cf4.s
    asm/dump/8057b80-debug/8063d38.s
    asm/dump/8057b80-debug/8063dac.s
    asm/dump/8057b80-debug/8063ddc-nullsub_16.s
    asm/dump/8057b80-debug/8063de0-nullsub_21.s
    asm/dump/8057b80-debug/8063de4-nullsub_22.s
    asm/dump/8057b80-debug/8063de8.s
    asm/dump/8057b80-debug/8063df0.s
    asm/dump/8057b80-debug/8063e18.s
    asm/dump/8057b80-debug/8063f40.s
    asm/dump/8057b80-debug/8063f5c.s
    asm/dump/8057b80-debug/8063f64.s
    asm/dump/8057b80-debug/8063f84.s
    asm/dump/8057b80-debug/80640f8.s
    asm/dump/8057b80-debug/8064104-pushTeletypeStringPalette.s
    asm/dump/8057b80-debug/8064130.s
    asm/dump/8057b80-debug/8064140.s
    asm/dump/8057b80-debug/806415c.s
    asm/dump/8057b80-debug/806417c.s
    asm/dump/8057b80-debug/8064188.s
    asm/dump/8064f38/8064f38.s
    asm/dump/8064f38/8064f50.s
    asm/dump/8064f38/8064f84.s
    asm/dump/8064f38/8064f9c.s
    asm/dump/8064f38/8064fe8-SpriteString_8064FE8.s
    asm/dump/8064f38/8065088.s
    asm/dump/8064f38/80650e0.s
    asm/dump/8064f38/80650f8.s
    asm/dump/8064f38/80650fc.s
    asm/dump/8064f38/8065108.s
    asm/dump/8064f38/806513e.s
    asm/dump/8064f38/806530c.s
    asm/dump/8064f38/8065334.s
    asm/dump/8064f38/80653b0.s
    asm/dump/8064f38/80653d8.s
    asm/dump/8064f38/8065508.s
    asm/dump/8064f38/80655c0.s
    asm/dump/8064f38/80656b8.s
    asm/dump/8064f38/806570c.s
    asm/dump/8064f38/8065760.s
    asm/dump/8064f38/80657c4.s
    asm/dump/8064f38/80657ec.s
    asm/dump/8064f38/8065804-initBatteryBackup.s
    asm/dump/8064f38/8065848-onTimer2Overflow.s
    asm/dump/8064f38/806586c.s
    asm/dump/8064f38/80658a4.s
    asm/dump/8064f38/806592c.s
    asm/dump/8064f38/8065970-DMA3Copy.s
    asm/dump/8064f38/80659f0.s
    asm/dump/8064f38/8065aa0.s
    asm/dump/8064f38/8065b7c-writeToBatteryBackup.s
    asm/dump/8064f38/8065bd4.s
    asm/dump/sound/80627f0.s
    asm/dump/sound/8062c24.s
    data/1-1/geometry.s
    data/1-1/metadata.s
    data/1-2/geometry.s
    data/1-2/metadata.s
    data/1-3/geometry.s
    data/1-3/metadata.s
    data/1-4/geometry.s
    data/1-4/metadata.s
    data/1-5/geometry.s
    data/1-5/metadata.s
    data/1-6/geometry.s
    data/1-6/metadata.s
    data/1-7/geometry.s
    data/1-7/metadata.s
    data/1-8/geometry.s
    data/1-8/metadata.s
    data/2-1/geometry.s
    data/2-1/metadata.s
    data/2-2/geometry.s
    data/2-2/metadata.s
    data/2-3/geometry.s
    data/2-3/metadata.s
    data/2-4/geometry.s
    data/2-4/metadata.s
    data/2-5/geometry.s
    data/2-5/metadata.s
    data/2-6/geometry.s
    data/2-6/metadata.s
    data/2-7/geometry.s
    data/2-7/metadata.s
    data/2-8/geometry.s
    data/2-8/metadata.s
    data/3-1/geometry.s
    data/3-1/metadata.s
    data/3-2/geometry.s
    data/3-2/metadata.s
    data/3-3/geometry.s
    data/3-3/metadata.s
    data/3-4/geometry.s
    data/3-4/metadata.s
    data/3-5/geometry.s
    data/3-5/metadata.s
    data/3-6/geometry.s
    data/3-6/metadata.s
    data/3-7/geometry.s
    data/3-7/metadata.s
    data/3-8/geometry.s
    data/3-8/metadata.s
    data/4-1/geometry.s
    data/4-1/metadata.s
    data/4-2/geometry.s
    data/4-2/metadata.s
    data/4-3/geometry.s
    data/4-3/metadata.s
    data/4-4/geometry.s
    data/4-4/metadata.s
    data/4-5/geometry.s
    data/4-5/metadata.s
    data/4-6/geometry.s
    data/4-6/metadata.s
    data/4-7/geometry.s
    data/4-7/metadata.s
    data/4-8/geometry.s
    data/4-8/metadata.s
    data/5-1/geometry.s
    data/5-1/metadata.s
    data/5-2/geometry.s
    data/5-2/metadata.s
    data/5-3/geometry.s
    data/5-3/metadata.s
    data/5-4/geometry.s
    data/5-4/metadata.s
    data/5-5/geometry.s
    data/5-5/metadata.s
    data/5-6/geometry.s
    data/5-6/metadata.s
    data/5-7/geometry.s
    data/5-7/metadata.s
    data/5-8/geometry.s
    data/5-8/metadata.s
    data/6-1/geometry.s
    data/6-1/metadata.s
    data/6-2/geometry.s
    data/6-2/metadata.s
    data/6-3/geometry.s
    data/6-3/metadata.s
    data/6-4/geometry.s
    data/6-4/metadata.s
    data/6-5/geometry.s
    data/6-5/metadata.s
    data/6-6/geometry.s
    data/6-6/metadata.s
    data/6-7/geometry.s
    data/6-7/metadata.s
    data/6-8/geometry.s
    data/6-8/metadata.s
    data/7-1/geometry.s
    data/7-1/metadata.s
    data/7-2/geometry.s
    data/7-2/metadata.s
    data/7-3/geometry.s
    data/7-3/metadata.s
    data/7-4/geometry.s
    data/7-4/metadata.s
    data/7-5/geometry.s
    data/7-5/metadata.s
    data/7-6/geometry.s
    data/7-6/metadata.s
    data/7-7/geometry.s
    data/7-7/metadata.s
    data/7-8/geometry.s
    data/7-8/metadata.s
    src/background.c
    src/bios.c
    src/irq.c
    src/keystate.c
    src/layer.c
    src/libc.c
    src/main.c
    src/memory.c
    src/ram.c
    src/ram2.c
    src/ram3.c
    src/sound.c
    src/sprite.c
    src/strings0.c
    src/strings3.c
    src/strings4.c
    src/strings5.c
    src/strings6.c
    src/strings7.c
)

include(cmake/gba.cmake OPTIONAL)
