cmake_minimum_required(VERSION 3.21)

project(beybladevforce LANGUAGES C ASM)

if(CMAKE_BINARY_DIR STREQUAL CMAKE_SOURCE_DIR)
    message(FATAL_ERROR "Building in-source is not supported. Remove CMakeCache.txt and use a separate build directory.")
endif()

set(CMAKE_EXPORT_COMPILE_COMMANDS ON)

add_library(agb INTERFACE)
target_include_directories(agb INTERFACE "${CMAKE_SOURCE_DIR}/lib/agb/include")

add_executable(rom
    asm/arm1.s
    asm/arm2.s
    asm/audio0.s
    asm/audio1.s
    asm/audio2.s
    asm/crt0.s
    asm/data1.s
    asm/data10.s
    asm/data11.s
    asm/data12.s
    asm/data3.s
    asm/data5.s
    asm/data6.s
    asm/data7.s
    asm/data8.s
    asm/data9.s
    asm/dataA.s
    asm/dataB.s
    asm/dataC.s
    data/1-1/geometry.s
    data/1-1/metadata.s
    data/1-2/geometry.s
    data/1-2/metadata.s
    data/1-3/geometry.s
    data/1-3/metadata.s
    data/1-4/geometry.s
    data/1-4/metadata.s
    data/1-5/geometry.s
    data/1-5/metadata.s
    data/1-6/geometry.s
    data/1-6/metadata.s
    data/1-7/geometry.s
    data/1-7/metadata.s
    data/1-8/geometry.s
    data/1-8/metadata.s
    data/2-1/geometry.s
    data/2-1/metadata.s
    data/2-2/geometry.s
    data/2-2/metadata.s
    data/2-3/geometry.s
    data/2-3/metadata.s
    data/2-4/geometry.s
    data/2-4/metadata.s
    data/2-5/geometry.s
    data/2-5/metadata.s
    data/2-6/geometry.s
    data/2-6/metadata.s
    data/2-7/geometry.s
    data/2-7/metadata.s
    data/2-8/geometry.s
    data/2-8/metadata.s
    data/3-1/geometry.s
    data/3-1/metadata.s
    data/3-2/geometry.s
    data/3-2/metadata.s
    data/3-3/geometry.s
    data/3-3/metadata.s
    data/3-4/geometry.s
    data/3-4/metadata.s
    data/3-5/geometry.s
    data/3-5/metadata.s
    data/3-6/geometry.s
    data/3-6/metadata.s
    data/3-7/geometry.s
    data/3-7/metadata.s
    data/3-8/geometry.s
    data/3-8/metadata.s
    data/4-1/geometry.s
    data/4-1/metadata.s
    data/4-2/geometry.s
    data/4-2/metadata.s
    data/4-3/geometry.s
    data/4-3/metadata.s
    data/4-4/geometry.s
    data/4-4/metadata.s
    data/4-5/geometry.s
    data/4-5/metadata.s
    data/4-6/geometry.s
    data/4-6/metadata.s
    data/4-7/geometry.s
    data/4-7/metadata.s
    data/4-8/geometry.s
    data/4-8/metadata.s
    data/5-1/geometry.s
    data/5-1/metadata.s
    data/5-2/geometry.s
    data/5-2/metadata.s
    data/5-3/geometry.s
    data/5-3/metadata.s
    data/5-4/geometry.s
    data/5-4/metadata.s
    data/5-5/geometry.s
    data/5-5/metadata.s
    data/5-6/geometry.s
    data/5-6/metadata.s
    data/5-7/geometry.s
    data/5-7/metadata.s
    data/5-8/geometry.s
    data/5-8/metadata.s
    data/6-1/geometry.s
    data/6-1/metadata.s
    data/6-2/geometry.s
    data/6-2/metadata.s
    data/6-3/geometry.s
    data/6-3/metadata.s
    data/6-4/geometry.s
    data/6-4/metadata.s
    data/6-5/geometry.s
    data/6-5/metadata.s
    data/6-6/geometry.s
    data/6-6/metadata.s
    data/6-7/geometry.s
    data/6-7/metadata.s
    data/6-8/geometry.s
    data/6-8/metadata.s
    data/7-1/geometry.s
    data/7-1/metadata.s
    data/7-2/geometry.s
    data/7-2/metadata.s
    data/7-3/geometry.s
    data/7-3/metadata.s
    data/7-4/geometry.s
    data/7-4/metadata.s
    data/7-5/geometry.s
    data/7-5/metadata.s
    data/7-6/geometry.s
    data/7-6/metadata.s
    data/7-7/geometry.s
    data/7-7/metadata.s
    data/7-8/geometry.s
    data/7-8/metadata.s
    src/actor.c
    src/actorheap.c
    src/ai.c
    src/render.c
    src/anim.c
    src/animevent.c
    src/background.c
    src/backup.c
    src/battery.c
    src/beyblade.c
    src/bios.c
    src/camera.c
    src/code_8057944.c
    src/collectable.c
    src/collection.c
    src/collision.c
    src/credits.c
    src/debug.c
    src/dialogue.c
    src/display.c
    src/effects.c
    src/envactor.c
    src/event.c
    src/festate.c
    src/frontend.c
    src/gameinit.c
    src/gameloop.c
    src/gamestate.c
    src/geometry.c
    src/hud.c
    src/iconmenu.c
    src/irq.c
    src/keystate.c
    src/language.c
    src/layer.c
    src/levelhud.c
    src/levelrow.c
    src/levelselect.c
    src/libc.c
    src/main.c
    src/math.c
    src/memory.c
    src/menu.c
    src/menuobject.c
    src/motion.c
    src/multiplayer.c
    src/music.c
    src/packet.c
    src/palette.c
    src/particle.c
    src/profile.c
    src/projectile.c
    src/ram.c
    src/ram2.c
    src/ram3.c
    src/results.c
    src/rider.c
    src/riderphysics.c
    src/riderstate.c
    src/sound.c
    src/sprite.c
    src/spritestring.c
    src/spritetext.c
    src/system.c
    src/teletype.c
    src/text.c
    src/trail.c
    src/transition.c
    src/tutorial.c
    src/strings0.c
    src/strings3.c
    src/strings4.c
    src/strings5.c
    src/strings6.c
    src/strings7.c
)

target_link_libraries(rom PRIVATE agb)

include(cmake/gba.cmake OPTIONAL)
