#!/bin/sh
# Snapshot the current (matching) build's objects as the objdiff baseline.
set -e
cd "$(dirname "$0")/.."
echo "cd527c8c24e20e33913fc45199e64b3e6138a6e5  build/rom.gba" | shasum -c
rm -rf expected
mkdir expected
cp -R build/. expected/
echo "expected/ updated"
