#include "beyblade.h"

#include <agb/bios.h>
#include <agb/memory_map.h>

#include "debug.h"
#include "include_asm.h"
#include "memory.h"
#include "ram.h"
#include "unsorted.h"

void emptyBeybladeActorData(void)
{
    BeybladeActorData* record;
    s32 i;

    record = _gameData->actorData.records;
    _gameData->actorData.unk1E0 = 0xE;
    for (i = 0; i < 0x3C; i++) {
        record->block = NULL;
        record->unk4 = 0;
        record++;
    }
}

void deallocBeybladeActorData(void)
{
    BeybladeActorData* record;
    s32 i;

    record = _gameData->actorData.records;
    for (i = 0; i < 0x3C; i++) {
        if (record->block != NULL) {
            deallocateBlock(record->block);
            record->block = NULL;
        }
        record++;
    }
}

extern const SpriteSheet* RiderSpriteSheets[];

const SpriteSheet* getBeyBladeActorDataForIndex(s32 index)
{
    GameData* gameData;
    BeybladeActorCache* cache;
    BeybladeActorData* record;
    const BeybladeData* data;
    const SpriteSheet* spriteSheet;
    const SpriteSheet* result;
    s32 bit;

    gameData = _gameData;
    cache = &gameData->actorData;
    record = &cache->records[index];
    data = getBeybladeData0(index);
    spriteSheet = RiderSpriteSheets[index];
    if (index > 0x3B) {
        printf("request out of range in getBeyBladeActorDataForIndex() %i >= %i\n", index, 0x3C);
        return NULL;
    }
    if (data->unk31 != 0) {
        if (record->block != NULL) {
            result = record->block->address;
        } else {
            record->block = slowAllocate(spriteSheet->unk0 >> 8);
            if (record->block == NULL) {
                printf("Unable to the allocate memory for decompression buffer in "
                       "getBeyBladeActorDataForIndex()\n");
            }
            result = record->block->address;
            LZ77UnCompWram(spriteSheet, record->block->address);
            bit = 0;
            while (((gameData->actorData.unk1E0 >> bit) & 1) != 0 && bit <= 0xF) {
                bit++;
            }
            if (bit <= 0xF) {
                record->unk4 = bit;
                cache->unk1E0 |= 1 << bit;
            } else {
                printf("unable to allocate a suitable palette in getBeyBladeActorDataForIndex()\n");
            }
        }
    } else {
        result = spriteSheet;
    }
    return result;
}

extern const SpriteSheet SpriteSheet_8360A78;
extern const SpriteSheet SpriteSheet_8363FDC;
extern const SpriteSheet SpriteSheet_8367A90;
extern const SpriteSheet SpriteSheet_836B3FC;
extern const SpriteSheet SpriteSheet_836FA10;
extern const SpriteSheet SpriteSheet_8373534;
extern const SpriteSheet SpriteSheet_837720C;
extern const SpriteSheet SpriteSheet_837B0EC;
extern const SpriteSheet SpriteSheet_837F810;
extern const SpriteSheet SpriteSheet_8383214;
extern const SpriteSheet SpriteSheet_83878B0;
extern const SpriteSheet SpriteSheet_838C1A4;
extern const SpriteSheet SpriteSheet_838FA2C;
extern const SpriteSheet SpriteSheet_83944C4;
extern const SpriteSheet SpriteSheet_8397C68;
extern const SpriteSheet SpriteSheet_839B844;
extern const SpriteSheet SpriteSheet_839F11C;
extern const SpriteSheet SpriteSheet_83A2EA8;
extern const SpriteSheet SpriteSheet_83A6978;
extern const SpriteSheet SpriteSheet_83AA92C;
extern const SpriteSheet SpriteSheet_83AE7F8;
extern const SpriteSheet SpriteSheet_83B1FA8;
extern const SpriteSheet SpriteSheet_83B5A28;
extern const SpriteSheet SpriteSheet_83B9808;
extern const SpriteSheet SpriteSheet_83BE294;
extern const SpriteSheet SpriteSheet_83C2C88;
extern const SpriteSheet SpriteSheet_83C6A78;
extern const SpriteSheet SpriteSheet_83CBDC0;
extern const SpriteSheet SpriteSheet_83CF998;
extern const SpriteSheet SpriteSheet_83D3898;
extern const SpriteSheet SpriteSheet_83D70FC;
extern const SpriteSheet SpriteSheet_83DB684;
extern const SpriteSheet SpriteSheet_83DF918;
extern const SpriteSheet SpriteSheet_83E34B0;
extern const SpriteSheet SpriteSheet_83E74CC;
extern const SpriteSheet SpriteSheet_83EAA9C;
extern const SpriteSheet SpriteSheet_83F0DFC;
extern const SpriteSheet SpriteSheet_83F91DC;
extern const SpriteSheet SpriteSheet_83FCE88;
extern const SpriteSheet SpriteSheet_84008A4;
extern const SpriteSheet SpriteSheet_8404590;
extern const SpriteSheet SpriteSheet_8408670;
extern const SpriteSheet SpriteSheet_840E0DC;
extern const SpriteSheet SpriteSheet_8411E2C;
extern const SpriteSheet SpriteSheet_8417254;
extern const SpriteSheet SpriteSheet_841AE9C;
extern const SpriteSheet SpriteSheet_841F928;
extern const SpriteSheet SpriteSheet_84247A0;
extern const SpriteSheet SpriteSheet_8429150;
extern const SpriteSheet SpriteSheet_842CD98;
extern const SpriteSheet SpriteSheet_8431474;
extern const SpriteSheet SpriteSheet_843508C;
extern const SpriteSheet SpriteSheet_8439290;
extern const SpriteSheet SpriteSheet_843E5A4;
extern const SpriteSheet SpriteSheet_8444750;
extern const SpriteSheet SpriteSheet_8449280;
extern const SpriteSheet SpriteSheet_844D140;
extern const SpriteSheet SpriteSheet_8451208;
extern const SpriteSheet SpriteSheet_84568FC;
extern const SpriteSheet SpriteSheet_845B08C;
extern const unk8 Pal_845EFA4[];
extern const unk8 Pal_845F1A4[];
extern const unk8 Pal_845F3A4[];
extern const unk8 Pal_845F5A4[];
extern const unk8 Pal_845F7A4[];
extern const unk8 Pal_845F9A4[];
extern const unk8 Pal_845FBA4[];
extern const unk8 Pal_845FDA4[];
extern const unk8 Pal_845FFA4[];
extern const unk8 Pal_84601A4[];
extern const unk8 Pal_84603A4[];
extern const unk8 Pal_84605A4[];
extern const unk8 Pal_84607A4[];
extern const unk8 Pal_84609A4[];
extern const unk8 Pal_8460BA4[];
extern const unk8 Pal_8460DA4[];
extern const unk8 Pal_8460FA4[];
extern const unk8 Pal_84611A4[];
extern const unk8 Pal_84613A4[];
extern const unk8 Pal_84615A4[];
extern const unk8 Pal_84617A4[];
extern const unk8 Pal_84619A4[];
extern const unk8 Pal_8461BA4[];
extern const unk8 Pal_8461DA4[];
extern const unk8 Pal_8461FA4[];
extern const unk8 Pal_84621A4[];
extern const unk8 Pal_84623A4[];
extern const unk8 Pal_84625A4[];
extern const unk8 Pal_84627A4[];
extern const unk8 Pal_84629A4[];
extern const unk8 Pal_8462BA4[];
extern const unk8 Pal_8462DA4[];
extern const unk8 Pal_8462FA4[];
extern const unk8 Pal_84631A4[];
extern const unk8 Pal_84633A4[];
extern const unk8 Pal_84635A4[];
extern const unk8 Pal_84637A4[];
extern const unk8 Pal_84639A4[];
extern const unk8 Pal_8463BA4[];
extern const unk8 Pal_8463DA4[];
extern const unk8 Pal_8463FA4[];
extern const unk8 Pal_84641A4[];
extern const unk8 Pal_84643A4[];
extern const unk8 Pal_84645A4[];
extern const unk8 Pal_84647A4[];
extern const unk8 Pal_84649A4[];
extern const unk8 Pal_8464BA4[];
extern const unk8 Pal_8464DA4[];
extern const unk8 Pal_8464FA4[];
extern const unk8 Pal_84651A4[];
extern const unk8 Pal_84653A4[];
extern const unk8 Pal_84655A4[];
extern const unk8 Pal_84657A4[];
extern const unk8 Pal_84659A4[];
extern const unk8 Pal_8465BA4[];
extern const unk8 Pal_8465DA4[];
extern const unk8 Pal_8465FA4[];
extern const unk8 Pal_84661A4[];
extern const unk8 Pal_84663A4[];
extern const unk8 Pal_84665A4[];
extern const unk8 Pal_8352C7C[];
extern const SpriteSheet SpriteSheet_8330070;
extern const unk8 Pal_8352E7C[];
extern const SpriteSheet SpriteSheet_83305DC;
extern const unk8 Pal_835307C[];
extern const SpriteSheet SpriteSheet_8330AB8;
extern const unk8 Pal_835327C[];
extern const SpriteSheet SpriteSheet_8330FC0;
extern const unk8 Pal_835347C[];
extern const SpriteSheet SpriteSheet_8331504;
extern const unk8 Pal_835367C[];
extern const SpriteSheet SpriteSheet_83319EC;
extern const unk8 Pal_835387C[];
extern const SpriteSheet SpriteSheet_8331EBC;
extern const unk8 Pal_8353A7C[];
extern const SpriteSheet SpriteSheet_8332344;
extern const unk8 Pal_8353C7C[];
extern const SpriteSheet SpriteSheet_833285C;
extern const unk8 Pal_8353E7C[];
extern const SpriteSheet SpriteSheet_8332E10;
extern const unk8 Pal_835407C[];
extern const SpriteSheet SpriteSheet_83332F4;
extern const unk8 Pal_835427C[];
extern const SpriteSheet SpriteSheet_83337C8;
extern const unk8 Pal_835447C[];
extern const SpriteSheet SpriteSheet_8333D28;
extern const unk8 Pal_835467C[];
extern const SpriteSheet SpriteSheet_833425C;
extern const unk8 Pal_835487C[];
extern const SpriteSheet SpriteSheet_833483C;
extern const unk8 Pal_8354A7C[];
extern const SpriteSheet SpriteSheet_8334E58;
extern const unk8 Pal_8354C7C[];
extern const SpriteSheet SpriteSheet_8335364;
extern const unk8 Pal_8354E7C[];
extern const SpriteSheet SpriteSheet_8335854;
extern const unk8 Pal_835507C[];
extern const SpriteSheet SpriteSheet_8335E4C;
extern const unk8 Pal_835527C[];
extern const SpriteSheet SpriteSheet_8336394;
extern const unk8 Pal_835547C[];
extern const SpriteSheet SpriteSheet_83367D0;
extern const unk8 Pal_835567C[];
extern const SpriteSheet SpriteSheet_8336BF4;
extern const unk8 Pal_835587C[];
extern const SpriteSheet SpriteSheet_8337104;
extern const unk8 Pal_8355A7C[];
extern const SpriteSheet SpriteSheet_8337708;
extern const unk8 Pal_8355C7C[];
extern const SpriteSheet SpriteSheet_8337BF0;
extern const unk8 Pal_8355E7C[];
extern const SpriteSheet SpriteSheet_833812C;
extern const unk8 Pal_835607C[];
extern const SpriteSheet SpriteSheet_83386B4;
extern const unk8 Pal_835627C[];
extern const SpriteSheet SpriteSheet_8338C5C;
extern const unk8 Pal_835647C[];
extern const SpriteSheet SpriteSheet_833916C;
extern const unk8 Pal_835667C[];
extern const SpriteSheet SpriteSheet_833973C;
extern const unk8 Pal_835687C[];
extern const SpriteSheet SpriteSheet_8339C44;
extern const unk8 Pal_8356A7C[];
extern const SpriteSheet SpriteSheet_833A120;
extern const unk8 Pal_8356C7C[];
extern const SpriteSheet SpriteSheet_833A7C8;
extern const unk8 Pal_8356E7C[];
extern const SpriteSheet SpriteSheet_833AE30;
extern const unk8 Pal_835707C[];
extern const SpriteSheet SpriteSheet_833B44C;
extern const unk8 Pal_835727C[];
extern const SpriteSheet SpriteSheet_833B974;
extern const unk8 Pal_835747C[];
extern const SpriteSheet SpriteSheet_833BF64;
extern const unk8 Pal_835767C[];
extern const SpriteSheet SpriteSheet_833C418;
extern const unk8 Pal_835787C[];
extern const SpriteSheet SpriteSheet_833C968;
extern const unk8 Pal_8357A7C[];
extern const SpriteSheet SpriteSheet_833CF10;
extern const unk8 Pal_8357C7C[];
extern const SpriteSheet SpriteSheet_833D474;
extern const unk8 Pal_8357E7C[];
extern const SpriteSheet SpriteSheet_833DA1C;
extern const unk8 Pal_835807C[];
extern const SpriteSheet SpriteSheet_833DFD4;
extern const unk8 Pal_835827C[];
extern const SpriteSheet SpriteSheet_833E65C;
extern const unk8 Pal_835847C[];
extern const SpriteSheet SpriteSheet_833EC5C;
extern const unk8 Pal_835867C[];
extern const SpriteSheet SpriteSheet_833F214;
extern const unk8 Pal_835887C[];
extern const SpriteSheet SpriteSheet_833F69C;
extern const unk8 Pal_8358A7C[];
extern const SpriteSheet SpriteSheet_833FBE8;
extern const unk8 Pal_8358C7C[];
extern const SpriteSheet SpriteSheet_8340180;
extern const unk8 Pal_8358E7C[];
extern const SpriteSheet SpriteSheet_83406BC;
extern const unk8 Pal_835907C[];
extern const SpriteSheet SpriteSheet_8340C60;
extern const unk8 Pal_835927C[];
extern const SpriteSheet SpriteSheet_834118C;
extern const unk8 Pal_835947C[];
extern const SpriteSheet SpriteSheet_83417B8;
extern const unk8 Pal_835967C[];
extern const SpriteSheet SpriteSheet_8341DAC;
extern const unk8 Pal_835987C[];
extern const SpriteSheet SpriteSheet_8342404;
extern const unk8 Pal_8359A7C[];
extern const SpriteSheet SpriteSheet_834298C;
extern const unk8 Pal_8359C7C[];
extern const SpriteSheet SpriteSheet_8342EA0;
extern const unk8 Pal_8359E7C[];
extern const SpriteSheet SpriteSheet_8343370;
extern const unk8 Pal_835A07C[];
extern const SpriteSheet SpriteSheet_83438F0;
extern const unk8 Pal_835A27C[];
extern const SpriteSheet SpriteSheet_8343E80;

const SpriteSheet* RiderSpriteSheets[] = {
    &SpriteSheet_8360A78,
    &SpriteSheet_8363FDC,
    &SpriteSheet_8367A90,
    &SpriteSheet_836B3FC,
    &SpriteSheet_836FA10,
    &SpriteSheet_8373534,
    &SpriteSheet_837720C,
    &SpriteSheet_837B0EC,
    &SpriteSheet_837F810,
    &SpriteSheet_8383214,
    &SpriteSheet_83878B0,
    &SpriteSheet_838C1A4,
    &SpriteSheet_838FA2C,
    &SpriteSheet_83944C4,
    &SpriteSheet_8397C68,
    &SpriteSheet_839B844,
    &SpriteSheet_839F11C,
    &SpriteSheet_83A2EA8,
    &SpriteSheet_83A6978,
    &SpriteSheet_83AA92C,
    &SpriteSheet_83AE7F8,
    &SpriteSheet_83B1FA8,
    &SpriteSheet_83B5A28,
    &SpriteSheet_83B9808,
    &SpriteSheet_83BE294,
    &SpriteSheet_83C2C88,
    &SpriteSheet_83C6A78,
    &SpriteSheet_83CBDC0,
    &SpriteSheet_83CF998,
    &SpriteSheet_83D3898,
    &SpriteSheet_83D70FC,
    &SpriteSheet_83DB684,
    &SpriteSheet_83DF918,
    &SpriteSheet_83E34B0,
    &SpriteSheet_83E74CC,
    &SpriteSheet_83EAA9C,
    &SpriteSheet_83F0DFC,
    &SpriteSheet_83F91DC,
    &SpriteSheet_83FCE88,
    &SpriteSheet_84008A4,
    &SpriteSheet_8404590,
    &SpriteSheet_8408670,
    &SpriteSheet_840E0DC,
    &SpriteSheet_8411E2C,
    &SpriteSheet_8417254,
    &SpriteSheet_841AE9C,
    &SpriteSheet_841F928,
    &SpriteSheet_84247A0,
    &SpriteSheet_8429150,
    &SpriteSheet_842CD98,
    &SpriteSheet_8431474,
    &SpriteSheet_843508C,
    &SpriteSheet_8439290,
    &SpriteSheet_843E5A4,
    &SpriteSheet_8444750,
    &SpriteSheet_8449280,
    &SpriteSheet_844D140,
    &SpriteSheet_8451208,
    &SpriteSheet_84568FC,
    &SpriteSheet_845B08C,
};

const unk8* RiderPalettes[] = {
    Pal_845EFA4,
    Pal_845F1A4,
    Pal_845F3A4,
    Pal_845F5A4,
    Pal_845F7A4,
    Pal_845F9A4,
    Pal_845FBA4,
    Pal_845FDA4,
    Pal_845FFA4,
    Pal_84601A4,
    Pal_84603A4,
    Pal_84605A4,
    Pal_84607A4,
    Pal_84609A4,
    Pal_8460BA4,
    Pal_8460DA4,
    Pal_8460FA4,
    Pal_84611A4,
    Pal_84613A4,
    Pal_84615A4,
    Pal_84617A4,
    Pal_84619A4,
    Pal_8461BA4,
    Pal_8461DA4,
    Pal_8461FA4,
    Pal_84621A4,
    Pal_84623A4,
    Pal_84625A4,
    Pal_84627A4,
    Pal_84629A4,
    Pal_8462BA4,
    Pal_8462DA4,
    Pal_8462FA4,
    Pal_84631A4,
    Pal_84633A4,
    Pal_84635A4,
    Pal_84637A4,
    Pal_84639A4,
    Pal_8463BA4,
    Pal_8463DA4,
    Pal_8463FA4,
    Pal_84641A4,
    Pal_84643A4,
    Pal_84645A4,
    Pal_84647A4,
    Pal_84649A4,
    Pal_8464BA4,
    Pal_8464DA4,
    Pal_8464FA4,
    Pal_84651A4,
    Pal_84653A4,
    Pal_84655A4,
    Pal_84657A4,
    Pal_84659A4,
    Pal_8465BA4,
    Pal_8465DA4,
    Pal_8465FA4,
    Pal_84661A4,
    Pal_84663A4,
    Pal_84665A4,
};

BeybladeData _807ac28[] = {
    { { "Ultimate Dragoon", "Ultimate Dragoon", "Ultimate Dragoon", "Ultimate Dragoon",
          "Ultimate Dragoon" },
        { "Attack", "Attack", "Attack", "Attack", "Attack" }, Pal_8352C7C, &SpriteSheet_8330070, 0,
        1 },
    { { "Ultimate Saizo", "Ultimate Saizo", "Ultimate Saizo", "Ultimate Saizo", "Ultimate Saizo" },
        { "Attack", "Attack", "Attack", "Attack", "Attack" }, Pal_8352E7C, &SpriteSheet_83305DC, 0,
        1 },
    { { "Ultimate Frostic Dranzer", "Ultimate Frostic Dranzer", "Ultimate Frostic Dranzer",
          "Ultimate Frostic Dranzer", "Ultimate Frostic Dranzer" },
        { "Attack", "Attack", "Attack", "Attack", "Attack" }, Pal_835307C, &SpriteSheet_8330AB8, 0,
        1 },
    { { "Gekiryu-Oh", "Gekiryu-Oh", "Gekiryu-Oh", "Gekiryu-Oh", "Gekiryu-Oh" },
        { "Attack", "Attack", "Attack", "Attack", "Attack" }, Pal_835327C, &SpriteSheet_8330FC0, 0,
        1 },
    { { "Megaro Arm", "Megaro Arm", "Megaro Arm", "Megaro Arm", "Megaro Arm" },
        { "Attack", "Attack", "Attack", "Attack", "Attack" }, Pal_835347C, &SpriteSheet_8331504, 0,
        1 },
    { { "Spark Knight", "Spark Knight", "Spark Knight", "Spark Knight", "Spark Knight" },
        { "Attack", "Attack", "Attack", "Attack", "Attack" }, Pal_835367C, &SpriteSheet_83319EC, 0,
        1 },
    { { "Polta", "Polta", "Polta", "Polta", "Polta" },
        { "Attack", "Attack", "Attack", "Attack", "Attack" }, Pal_835387C, &SpriteSheet_8331EBC, 0,
        1 },
    { { "Pistol", "Pistol", "Pistol", "Pistol", "Pistol" },
        { "Attack", "Attack", "Attack", "Attack", "Attack" }, Pal_8353A7C, &SpriteSheet_8332344, 0,
        1 },
    { { "Makendo", "Makendo", "Makendo", "Makendo", "Makendo" },
        { "Attack", "Attack", "Attack", "Attack", "Attack" }, Pal_8353C7C, &SpriteSheet_833285C, 0,
        1 },
    { { "Bakushin", "Bakushin", "Bakushin", "Bakushin", "Bakushin" },
        { "Attack", "Attack", "Attack", "Attack", "Attack" }, Pal_8353E7C, &SpriteSheet_8332E10, 0,
        1 },
    { { "Bump King", "Bump King", "Bump King", "Bump King", "Bump King" },
        { "Attack", "Attack", "Attack", "Attack", "Attack" }, Pal_835407C, &SpriteSheet_83332F4, 0,
        1 },
    { { "Grip Attacker", "Grip Attacker", "Grip Attacker", "Grip Attacker", "Grip Attacker" },
        { "Attack", "Attack", "Attack", "Attack", "Attack" }, Pal_835427C, &SpriteSheet_83337C8, 0,
        1 },
    { { "Bearing Stinger", "Bearing Stinger", "Bearing Stinger", "Bearing Stinger",
          "Bearing Stinger" },
        { "Attack", "Attack", "Attack", "Attack", "Attack" }, Pal_835447C, &SpriteSheet_8333D28, 0,
        1 },
    { { "Bound Attacker", "Bound Attacker", "Bound Attacker", "Bound Attacker", "Bound Attacker" },
        { "Attack", "Attack", "Attack", "Attack", "Attack" }, Pal_835467C, &SpriteSheet_833425C, 0,
        1 },
    { { "Bound Defender", "Bound Defender", "Bound Defender", "Bound Defender", "Bound Defender" },
        { "Attack", "Attack", "Attack", "Attack", "Attack" }, Pal_835487C, &SpriteSheet_833483C, 0,
        1 },
    { { "Roller Attacker", "Roller Attacker", "Roller Attacker", "Roller Attacker",
          "Roller Attacker" },
        { "Attack", "Attack", "Attack", "Attack", "Attack" }, Pal_8354A7C, &SpriteSheet_8334E58, 0,
        1 },
    { { "Roller Defenser", "Roller Defenser", "Roller Defenser", "Roller Defenser",
          "Roller Defenser" },
        { "Attack", "Attack", "Attack", "Attack", "Attack" }, Pal_8354C7C, &SpriteSheet_8335364, 0,
        1 },
    { { "Auto Change Balancer", "Auto Change Balancer", "Auto Change Balancer",
          "Auto Change Balancer", "Auto Change Balancer" },
        { "Attack", "Attack", "Attack", "Attack", "Attack" }, Pal_8354E7C, &SpriteSheet_8335854, 0,
        1 },
    { { "Wing Attacker", "Wing Attacker", "Wing Attacker", "Wing Attacker", "Wing Attacker" },
        { "Attack", "Attack", "Attack", "Attack", "Attack" }, Pal_835507C, &SpriteSheet_8335E4C, 0,
        1 },
    { { "Wing Defenser", "Wing Defenser", "Wing Defenser", "Wing Defenser", "Wing Defenser" },
        { "Attack", "Attack", "Attack", "Attack", "Attack" }, Pal_835527C, &SpriteSheet_8336394, 0,
        1 },
    { { "Draceil Metal", "Draceil Metal", "Draceil Metal", "Draceil Metal", "Draceil Metal" },
        { "Attack", "Attack", "Attack", "Attack", "Attack" }, Pal_835547C, &SpriteSheet_83367D0, 0,
        1 },
    { { "Dragoon Storm", "Dragoon Storm", "Dragoon Storm", "Dragoon Storm", "Dragoon Storm" },
        { "Attack", "Attack", "Attack", "Attack", "Attack" }, Pal_835567C, &SpriteSheet_8336BF4, 0,
        1 },
    { { "Driger S", "Driger S", "Driger S", "Driger S", "Driger S" },
        { "Attack", "Attack", "Attack", "Attack", "Attack" }, Pal_835587C, &SpriteSheet_8337104, 0,
        1 },
    { { "Death Driger", "Death Driger", "Death Driger", "Death Driger", "Death Driger" },
        { "Attack", "Attack", "Attack", "Attack", "Attack" }, Pal_8355A7C, &SpriteSheet_8337708, 0,
        1 },
    { { "Knight Dranzer", "Knight Dranzer", "Knight Dranzer", "Knight Dranzer", "Knight Dranzer" },
        { "Defense", "Defense", "Defense", "Defense", "Defense" }, Pal_8355C7C,
        &SpriteSheet_8337BF0, 0, 1 },
    { { "Metal Draceil", "Metal Draceil", "Metal Draceil", "Metal Draceil", "Metal Draceil" },
        { "Defense", "Defense", "Defense", "Defense", "Defense" }, Pal_8355E7C,
        &SpriteSheet_833812C, 0, 1 },
    { { "Kid Dragoon", "Kid Dragoon", "Kid Dragoon", "Kid Dragoon", "Kid Dragoon" },
        { "Attack", "Attack", "Attack", "Attack", "Attack" }, Pal_835607C, &SpriteSheet_83386B4, 0,
        1 },
    { { "Dragoon S", "Dragoon S", "Dragoon S", "Dragoon S", "Dragoon S" },
        { "Attack", "Attack", "Attack", "Attack", "Attack" }, Pal_835627C, &SpriteSheet_8338C5C, 0,
        1 },
    { { "Dranzer S", "Dranzer S", "Dranzer S", "Dranzer S", "Dranzer S" },
        { "Attack", "Attack", "Attack", "Attack", "Attack" }, Pal_835647C, &SpriteSheet_833916C, 0,
        1 },
    { { "Galeon Attacker", "Galeon Attacker", "Galeon Attacker", "Galeon Attacker",
          "Galeon Attacker" },
        { "Attack", "Attack", "Attack", "Attack", "Attack" }, Pal_835667C, &SpriteSheet_833973C, 0,
        1 },
    { { "Galzzly", "Galzzly", "Galzzly", "Galzzly", "Galzzly" },
        { "Defense", "Defense", "Defense", "Defense", "Defense" }, Pal_835687C,
        &SpriteSheet_8339C44, 0, 1 },
    { { "Galman", "Galman", "Galman", "Galman", "Galman" },
        { "Attack", "Attack", "Attack", "Attack", "Attack" }, Pal_8356A7C, &SpriteSheet_833A120, 0,
        1 },
    { { "Wolborg", "Wolborg", "Wolborg", "Wolborg", "Wolborg" },
        { "Attack", "Attack", "Attack", "Attack", "Attack" }, Pal_8356C7C, &SpriteSheet_833A7C8, 0,
        1 },
    { { "Seaborg", "Seaborg", "Seaborg", "Seaborg", "Seaborg" },
        { "Attack", "Attack", "Attack", "Attack", "Attack" }, Pal_8356E7C, &SpriteSheet_833AE30, 0,
        1 },
    { { "Draceil S", "Draceil S", "Draceil S", "Draceil S", "Draceil S" },
        { "Attack", "Attack", "Attack", "Attack", "Attack" }, Pal_835707C, &SpriteSheet_833B44C, 0,
        1 },
    { { "Trygle", "Trygle", "Trygle", "Trygle", "Trygle" },
        { "Attack", "Attack", "Attack", "Attack", "Attack" }, Pal_835727C, &SpriteSheet_833B974, 0,
        1 },
    { { "Trypio", "Trypio", "Trypio", "Trypio", "Trypio" },
        { "Attack", "Attack", "Attack", "Attack", "Attack" }, Pal_835747C, &SpriteSheet_833BF64, 0,
        1 },
    { { "Driger F", "Driger F", "Driger F", "Driger F", "Driger F" },
        { "Attack", "Attack", "Attack", "Attack", "Attack" }, Pal_835767C, &SpriteSheet_833C418, 0,
        1 },
    { { "Dragoon Fighter", "Dragoon Fighter", "Dragoon Fighter", "Dragoon Fighter",
          "Dragoon Fighter" },
        { "Attack", "Attack", "Attack", "Attack", "Attack" }, Pal_835787C, &SpriteSheet_833C968, 0,
        1 },
    { { "Dranzer F", "Dranzer F", "Dranzer F", "Dranzer F", "Dranzer F" },
        { "Attack", "Attack", "Attack", "Attack", "Attack" }, Pal_8357A7C, &SpriteSheet_833CF10, 0,
        1 },
    { { "Griffolyon", "Griffolyon", "Griffolyon", "Griffolyon", "Griffolyon" },
        { "Attack", "Attack", "Attack", "Attack", "Attack" }, Pal_8357C7C, &SpriteSheet_833D474, 0,
        1 },
    { { "Master Dragoon", "Master Dragoon", "Master Dragoon", "Master Dragoon", "Master Dragoon" },
        { "Attack", "Attack", "Attack", "Attack", "Attack" }, Pal_8357E7C, &SpriteSheet_833DA1C, 0,
        1 },
    { { "Master Dranzer", "Master Dranzer", "Master Dranzer", "Master Dranzer", "Master Dranzer" },
        { "Attack", "Attack", "Attack", "Attack", "Attack" }, Pal_835807C, &SpriteSheet_833DFD4, 0,
        1 },
    { { "Master Draceil", "Master Draceil", "Master Draceil", "Master Draceil", "Master Draceil" },
        { "Attack", "Attack", "Attack", "Attack", "Attack" }, Pal_835827C, &SpriteSheet_833E65C, 0,
        1 },
    { { "Draceil F", "Draceil F", "Draceil F", "Draceil F", "Draceil F" },
        { "Attack", "Attack", "Attack", "Attack", "Attack" }, Pal_835847C, &SpriteSheet_833EC5C, 0,
        1 },
    { { "Wyborg", "Wyborg", "Wyborg", "Wyborg", "Wyborg" },
        { "Attack", "Attack", "Attack", "Attack", "Attack" }, Pal_835867C, &SpriteSheet_833F214, 0,
        1 },
    { { "Master Driger", "Master Driger", "Master Driger", "Master Driger", "Master Driger" },
        { "Attack", "Attack", "Attack", "Attack", "Attack" }, Pal_835887C, &SpriteSheet_833F69C, 0,
        1 },
    { { "Wolborg 2", "Wolborg 2", "Wolborg 2", "Wolborg 2", "Wolborg 2" },
        { "Attack", "Attack", "Attack", "Attack", "Attack" }, Pal_8358A7C, &SpriteSheet_833FBE8, 0,
        1 },
    { { "Dragoon V", "Dragoon V", "Dragoon V", "Dragoon V", "Dragoon V" },
        { "Attack", "Attack", "Attack", "Attack", "Attack" }, Pal_8358C7C, &SpriteSheet_8340180, 0,
        1 },
    { { "Metal Dranzer", "Metal Dranzer", "Metal Dranzer", "Metal Dranzer", "Metal Dranzer" },
        { "Attack", "Attack", "Attack", "Attack", "Attack" }, Pal_8358E7C, &SpriteSheet_83406BC, 0,
        1 },
    { { "Flash Leopard", "Flash Leopard", "Flash Leopard", "Flash Leopard", "Flash Leopard" },
        { "Attack", "Attack", "Attack", "Attack", "Attack" }, Pal_835907C, &SpriteSheet_8340C60, 0,
        1 },
    { { "Driger V", "Driger V", "Driger V", "Driger V", "Driger V" },
        { "Defense", "Defense", "Defense", "Defense", "Defense" }, Pal_835927C,
        &SpriteSheet_834118C, 0, 1 },
    { { "Dranzer V", "Dranzer V", "Dranzer V", "Dranzer V", "Dranzer V" },
        { "Attack", "Attack", "Attack", "Attack", "Attack" }, Pal_835947C, &SpriteSheet_83417B8, 0,
        1 },
    { { "Cyber Dragoon", "Cyber Dragoon", "Cyber Dragoon", "Cyber Dragoon", "Cyber Dragoon" },
        { "Attack", "Attack", "Attack", "Attack", "Attack" }, Pal_835967C, &SpriteSheet_8341DAC, 0,
        1 },
    { { "Draceil V", "Draceil V", "Draceil V", "Draceil V", "Draceil V" },
        { "Attack", "Attack", "Attack", "Attack", "Attack" }, Pal_835987C, &SpriteSheet_8342404, 0,
        1 },
    { { "Hayate Hidden Spirit", "Hayate Hidden Spirit", "Hayate Hidden Spirit",
          "Hayate Hidden Spirit", "Hayate Hidden Spirit" },
        { "Attack", "Attack", "Attack", "Attack", "Attack" }, Pal_8359A7C, &SpriteSheet_834298C, 0,
        1 },
    { { "Zinrai Hidden Spirit", "Zinrai Hidden Spirit", "Zinrai Hidden Spirit",
          "Zinrai Hidden Spirit", "Zinrai Hidden Spirit" },
        { "Attack", "Attack", "Attack", "Attack", "Attack" }, Pal_8359C7C, &SpriteSheet_8342EA0, 0,
        1 },
    { { "Cyber Dranzer", "Cyber Dranzer", "Cyber Dranzer", "Cyber Dranzer", "Cyber Dranzer" },
        { "Attack", "Attack", "Attack", "Attack", "Attack" }, Pal_8359E7C, &SpriteSheet_8343370, 0,
        1 },
    { { "Cyber Draceil", "Cyber Draceil", "Cyber Draceil", "Cyber Draceil", "Cyber Draceil" },
        { "Attack", "Attack", "Attack", "Attack", "Attack" }, Pal_835A07C, &SpriteSheet_83438F0, 0,
        1 },
    { { "Cyber Driger", "Cyber Driger", "Cyber Driger", "Cyber Driger", "Cyber Driger" },
        { "Attack", "Attack", "Attack", "Attack", "Attack" }, Pal_835A27C, &SpriteSheet_8343E80, 0,
        1 },
};

unk8 _807b858[][12] = {
    { 2, 1, 2, 0, 1, 1, 3, 0, 3, 2, 1, 0 },
    { 2, 1, 1, 0, 1, 3, 1, 0, 1, 2, 3, 0 },
    { 1, 2, 3, 0, 1, 1, 2, 0, 2, 2, 2, 0 },
    { 1, 2, 3, 0, 1, 1, 3, 0, 2, 2, 2, 0 },
    { 2, 1, 2, 0, 1, 3, 1, 0, 3, 2, 1, 0 },
    { 2, 1, 1, 0, 1, 2, 2, 0, 1, 2, 3, 0 },
    { 2, 1, 1, 0, 1, 1, 3, 0, 1, 2, 3, 0 },
    { 1, 2, 3, 0, 1, 2, 2, 0, 2, 2, 2, 0 },
    { 2, 1, 2, 0, 1, 2, 2, 0, 3, 2, 1, 0 },
    { 1, 3, 1, 0, 1, 3, 1, 0, 3, 2, 1, 0 },
    { 2, 2, 1, 0, 1, 1, 3, 0, 1, 2, 2, 0 },
    { 2, 1, 2, 0, 1, 1, 3, 0, 4, 1, 1, 0 },
    { 2, 1, 2, 0, 1, 3, 1, 0, 1, 1, 4, 0 },
    { 3, 2, 1, 0, 3, 2, 1, 0, 3, 2, 1, 0 },
    { 2, 3, 2, 0, 2, 3, 2, 0, 2, 3, 2, 0 },
    { 2, 2, 1, 0, 1, 2, 2, 0, 3, 2, 1, 0 },
    { 1, 3, 1, 0, 1, 3, 1, 0, 2, 2, 1, 0 },
    { 2, 2, 2, 0, 1, 2, 2, 0, 3, 2, 3, 0 },
    { 3, 3, 1, 0, 1, 1, 3, 0, 2, 2, 2, 0 },
    { 2, 2, 1, 0, 1, 3, 1, 0, 2, 2, 2, 0 },
    { 1, 2, 3, 0, 1, 3, 2, 0, 1, 2, 4, 0 },
    { 2, 1, 2, 0, 1, 1, 4, 0, 4, 1, 1, 0 },
    { 1, 3, 2, 0, 1, 3, 2, 0, 3, 1, 1, 0 },
    { 1, 3, 3, 0, 1, 3, 3, 0, 1, 3, 3, 0 },
    { 3, 2, 1, 0, 1, 2, 3, 0, 2, 2, 2, 0 },
    { 1, 2, 3, 0, 1, 3, 2, 0, 1, 2, 4, 0 },
    { 3, 1, 1, 0, 1, 1, 3, 0, 3, 2, 1, 0 },
    { 2, 2, 2, 0, 1, 1, 4, 0, 4, 1, 1, 0 },
    { 2, 2, 2, 0, 1, 2, 3, 0, 3, 2, 3, 0 },
    { 3, 3, 1, 0, 1, 3, 2, 0, 2, 2, 2, 0 },
    { 4, 2, 1, 0, 1, 1, 4, 0, 3, 2, 1, 0 },
    { 1, 4, 2, 0, 1, 3, 2, 0, 1, 2, 3, 0 },
    { 2, 3, 2, 0, 1, 2, 3, 0, 1, 2, 3, 0 },
    { 3, 1, 2, 0, 1, 1, 4, 0, 1, 3, 1, 0 },
    { 3, 2, 1, 0, 1, 2, 3, 0, 1, 3, 4, 0 },
    { 2, 2, 1, 0, 1, 1, 4, 0, 4, 1, 1, 0 },
    { 1, 2, 1, 0, 1, 3, 2, 0, 1, 2, 3, 0 },
    { 3, 3, 2, 0, 1, 2, 3, 0, 4, 1, 3, 0 },
    { 3, 3, 3, 0, 1, 1, 4, 0, 4, 1, 1, 0 },
    { 2, 3, 2, 0, 1, 3, 2, 0, 3, 2, 3, 0 },
    { 2, 2, 2, 0, 2, 2, 2, 0, 2, 2, 2, 0 },
    { 3, 1, 2, 0, 1, 3, 2, 0, 3, 2, 1, 0 },
    { 1, 2, 3, 0, 1, 2, 3, 0, 1, 2, 4, 0 },
    { 2, 2, 2, 0, 1, 1, 4, 0, 1, 2, 3, 0 },
    { 3, 2, 2, 0, 1, 2, 3, 0, 1, 4, 4, 0 },
    { 2, 2, 1, 0, 1, 3, 2, 0, 3, 2, 4, 0 },
    { 3, 2, 1, 0, 2, 1, 3, 0, 2, 2, 2, 0 },
    { 3, 1, 1, 0, 1, 2, 3, 0, 3, 2, 1, 0 },
    { 3, 3, 3, 0, 1, 1, 4, 0, 4, 1, 1, 0 },
    { 2, 2, 3, 0, 1, 2, 3, 0, 3, 2, 1, 0 },
    { 1, 1, 1, 0, 1, 3, 2, 0, 1, 3, 2, 0 },
    { 3, 2, 2, 0, 1, 2, 3, 0, 3, 2, 2, 0 },
    { 3, 1, 2, 0, 1, 2, 3, 0, 2, 2, 2, 0 },
    { 3, 1, 1, 0, 1, 1, 4, 0, 3, 2, 1, 0 },
    { 3, 3, 2, 0, 1, 3, 2, 0, 1, 4, 3, 0 },
    { 2, 2, 2, 0, 2, 2, 2, 0, 2, 2, 2, 0 },
    { 2, 2, 2, 0, 2, 2, 2, 0, 2, 2, 2, 0 },
    { 1, 2, 3, 0, 1, 2, 3, 0, 1, 2, 4, 0 },
    { 2, 2, 2, 0, 1, 1, 4, 0, 1, 2, 3, 0 },
    { 3, 2, 1, 0, 2, 1, 3, 0, 2, 2, 2, 0 },
};

static const unk8* _807BB28[] = {
    "Attack Type",
    "Endurance Type",
    "Combination Type",
    "Combination Type",
    "Attack Type",
    "Endurance Type",
    "Endurance Type",
    "Combination Type",
    "Attack Type",
    "Attack Type",
    "Defense Type",
    "Attack Type",
    "Endurance Type",
    "Attack Type",
    "Defense Type",
    "Attack Type",
    "Defense Type",
    "Combination Type",
    "Attack Type",
    "Defense Type",
    "Defense Type",
    "Attack Type",
    "Combination Type",
    "Defense Type",
    "Attack Type",
    "Endurance Type",
    "Attack Type",
    "Attack Type",
    "Combination Type",
    "Combination Type",
    "Attack Type",
    "Defense Type",
    "Endurance Type",
    "Defense Type",
    "Defense Type",
    "Attack Type",
    "Defense Type",
    "Combination Type",
    "Attack Type",
    "Combination Type",
    "Attack Type",
    "Attack Type",
    "Endurance Type",
    "Defense Type",
    "Defense Type",
    "Combination Type",
    "Attack Type",
    "Combination Type",
    "Attack Type",
    "Attack Type",
    "Combination Type",
    "Attack Type",
    "Combination Type",
    "Combination Type",
    "Defense Type",
    "-",
    "-",
    "-",
    "-",
    "-",
};

static const unk8* _807BC18[] = {
    "Tipo de ataque",
    "Tipo de resistencia",
    "Tipo de combinación",
    "Tipo de combinación",
    "Tipo de ataque",
    "Tipo de resistencia",
    "Tipo de resistencia",
    "Tipo de combinación",
    "Tipo de ataque",
    "Tipo de ataque",
    "Tipo Defensa",
    "Tipo de ataque",
    "Tipo de resistencia",
    "Tipo de ataque",
    "Tipo Defensa",
    "Tipo de ataque",
    "Tipo Defensa",
    "Tipo de combinación",
    "Tipo de ataque",
    "Tipo Defensa",
    "Tipo Defensa",
    "Tipo de ataque",
    "Tipo de combinación",
    "Tipo Defensa",
    "Tipo de ataque",
    "Tipo de resistencia",
    "Tipo de ataque",
    "Tipo de ataque",
    "Tipo de combinación",
    "Tipo de combinación",
    "Tipo de ataque",
    "Tipo Defensa",
    "Tipo de resistencia",
    "Tipo Defensa",
    "Tipo Defensa",
    "Tipo de ataque",
    "Tipo Defensa",
    "Tipo de combinación",
    "Tipo de ataque",
    "Tipo de combinación",
    "Tipo de ataque",
    "Tipo de ataque",
    "Tipo de resistencia",
    "Tipo Defensa",
    "Tipo Defensa",
    "Tipo de combinación",
    "Tipo de ataque",
    "Tipo de combinación",
    "Tipo de ataque",
    "Tipo de ataque",
    "Tipo de combinación",
    "Tipo de ataque",
    "Tipo de combinación",
    "Tipo de combinación",
    "Tipo Defensa",
    "-",
    "-",
    "-",
    "-",
    "-",
};

static const unk8* _807BD08[] = {
    "Angriffsspezialist",
    "Ausdauerspezialist",
    "Kombinationsspezialist",
    "Kombinationsspezialist",
    "Angriffsspezialist",
    "Ausdauerspezialist",
    "Ausdauerspezialist",
    "Kombinationsspezialist",
    "Angriffsspezialist",
    "Angriffsspezialist",
    "Abwehrspezialist",
    "Angriffsspezialist",
    "Ausdauerspezialist",
    "Angriffsspezialist",
    "Abwehrspezialist",
    "Angriffsspezialist",
    "Abwehrspezialist",
    "Kombinationsspezialist",
    "Angriffsspezialist",
    "Abwehrspezialist",
    "Abwehrspezialist",
    "Angriffsspezialist",
    "Kombinationsspezialist",
    "Abwehrspezialist",
    "Angriffsspezialist",
    "Ausdauerspezialist",
    "Angriffsspezialist",
    "Angriffsspezialist",
    "Kombinationsspezialist",
    "Kombinationsspezialist",
    "Angriffsspezialist",
    "Abwehrspezialist",
    "Ausdauerspezialist",
    "Abwehrspezialist",
    "Abwehrspezialist",
    "Angriffsspezialist",
    "Abwehrspezialist",
    "Kombinationsspezialist",
    "Angriffsspezialist",
    "Kombinationsspezialist",
    "Angriffsspezialist",
    "Angriffsspezialist",
    "Ausdauerspezialist",
    "Abwehrspezialist",
    "Abwehrspezialist",
    "Kombinationsspezialist",
    "Angriffsspezialist",
    "Kombinationsspezialist",
    "Angriffsspezialist",
    "Angriffsspezialist",
    "Kombinationsspezialist",
    "Angriffsspezialist",
    "Kombinationsspezialist",
    "Kombinationsspezialist",
    "Abwehrspezialist",
    "-",
    "-",
    "-",
    "-",
    "-",
};

static const unk8* _807BDF8[] = {
    "Type d'attaque",
    "Type d'endurance",
    "Type de combinaison",
    "Type de combinaison",
    "Type d'attaque",
    "Type d'endurance",
    "Type d'endurance",
    "Type de combinaison",
    "Type d'attaque",
    "Type d'attaque",
    "Type de défense",
    "Type d'attaque",
    "Type d'endurance",
    "Type d'attaque",
    "Type de défense",
    "Type d'attaque",
    "Type de défense",
    "Type de combinaison",
    "Type d'attaque",
    "Type de défense",
    "Type de défense",
    "Type d'attaque",
    "Type de combinaison",
    "Type de défense",
    "Type d'attaque",
    "Type d'endurance",
    "Type d'attaque",
    "Type d'attaque",
    "Type de combinaison",
    "Type de combinaison",
    "Type d'attaque",
    "Type de défense",
    "Type d'endurance",
    "Type de défense",
    "Type de défense",
    "Type d'attaque",
    "Type de défense",
    "Type de combinaison",
    "Type d'attaque",
    "Type de combinaison",
    "Type d'attaque",
    "Type d'attaque",
    "Type d'endurance",
    "Type de défense",
    "Type de défense",
    "Type de combinaison",
    "Type d'attaque",
    "Type de combinaison",
    "Type d'attaque",
    "Type d'attaque",
    "Type de combinaison",
    "Type d'attaque",
    "Type de combinaison",
    "Type de combinaison",
    "Type de défense",
    "-",
    "-",
    "-",
    "-",
    "-",
};

static const unk8* _807BEE8[] = {
    "Tipo da attacco",
    "Tipo resistente",
    "Tipo combinato",
    "Tipo combinato",
    "Tipo da attacco",
    "Tipo resistente",
    "Tipo resistente",
    "Tipo combinato",
    "Tipo da attacco",
    "Tipo da attacco",
    "Tipo da difesa",
    "Tipo da attacco",
    "Tipo resistente",
    "Tipo da attacco",
    "Tipo da difesa",
    "Tipo da attacco",
    "Tipo da difesa",
    "Tipo combinato",
    "Tipo da attacco",
    "Tipo da difesa",
    "Tipo da difesa",
    "Tipo da attacco",
    "Tipo combinato",
    "Tipo da difesa",
    "Tipo da attacco",
    "Tipo resistente",
    "Tipo da attacco",
    "Tipo da attacco",
    "Tipo combinato",
    "Tipo combinato",
    "Tipo da attacco",
    "Tipo da difesa",
    "Tipo resistente",
    "Tipo da difesa",
    "Tipo da difesa",
    "Tipo da attacco",
    "Tipo da difesa",
    "Tipo combinato",
    "Tipo da attacco",
    "Tipo combinato",
    "Tipo da attacco",
    "Tipo da attacco",
    "Tipo resistente",
    "Tipo da difesa",
    "Tipo da difesa",
    "Tipo combinato",
    "Tipo da attacco",
    "Tipo combinato",
    "Tipo da attacco",
    "Tipo da attacco",
    "Tipo combinato",
    "Tipo da attacco",
    "Tipo combinato",
    "Tipo combinato",
    "Tipo da difesa",
    "-",
    "-",
    "-",
    "-",
    "-",
};

const unk8** _807BFD8[] = { _807BB28, _807BC18, _807BD08, _807BDF8, _807BEE8 };

static const unk8* _807BFEC[] = {
    "Ultimate Dragoon",
    "Saizo",
    "Frostic Dranzer",
    "Gekiryu-oh",
    "Megaro Arm",
    "Spark Knight",
    "Polta",
    "Pistol",
    "Ultimate Dragoon",
    "Bakushin-oh",
    "Bump King",
    "Dragoon",
    "Metal Dragoon",
    "Random",
    "Random",
    "Random",
    "Random",
    "Dranzer",
    "Random",
    "Random",
    "Draciel",
    "Dragoon",
    "Driger",
    "Death Driger",
    "Knight Dranzer",
    "Metal Draciel",
    "Kid Dragoon",
    "Dragoon Storm",
    "Dranzer",
    "Galeon",
    "Galzzly",
    "Galman",
    "Wolborg",
    "Seaborg",
    "Draciel",
    "Trygle",
    "Trypio",
    "Driger Slash",
    "Dragoon",
    "Dranzer Spiral",
    "Griffolyon",
    "Master Dragoon",
    "Master Dranzer",
    "Master Draciel",
    "Draciel",
    "Wyborg",
    "Master Driger",
    "Wolborg",
    "Dragoon",
    "Metal Dranzer",
    "Flash Leopard",
    "Driger",
    "Dranzer",
    "Cyber Dragoon",
    "Draciel",
    "-",
    "-",
    "-",
    "-",
    "-",
};

static const unk8* _807C0DC[] = {
    "Dragón Definitivo",
    "Saizo",
    "Dranzer Helado",
    "Gekiryu-oh",
    "Brazo Megaro",
    "Caballero de las Chispas",
    "Polta",
    "Pistola",
    "Dragón Definitivo",
    "Bakushin-oh",
    "Rey de las Bombas",
    "Dragón",
    "Dragón de Metal",
    "Aleatorio",
    "Aleatorio",
    "Aleatorio",
    "Aleatorio",
    "Dranzer",
    "Aleatorio",
    "Aleatorio",
    "Draciel",
    "Dragón",
    "Driger",
    "Driger Mortal",
    "Caballero Dranzer",
    "Draciel Metálico",
    "Niño Dragoon",
    "Tormenta Dragón",
    "Dranzer",
    "Galeón",
    "Galzzly",
    "Galman",
    "Wolborg",
    "Seaborg",
    "Draciel",
    "Trygle",
    "Trypio",
    "Driger Slash",
    "Dragón",
    "Espiral Dranzer",
    "Griffolyon",
    "Maestro Dragón",
    "Maestro Dranzer",
    "Maestro Draciel",
    "Draciel",
    "Wyborg",
    "Mestro Driger",
    "Wolborg",
    "Dragón",
    "Dranzer Metálico",
    "Leopardo Relámpago",
    "Driger",
    "Dranzer",
    "Cíber Dragón",
    "Draciel",
    "-",
    "-",
    "-",
    "-",
    "-",
};

static const unk8* _807C1CC[] = {
    "Ultimate Dragoon",
    "Saizo",
    "Frostic Dranzer",
    "Gekiryu-oh",
    "Megaro Arm",
    "Spark Knight",
    "Polta",
    "Pistol",
    "Ultimate Dragoon",
    "Bakushin-oh",
    "Bump King",
    "Dragoon",
    "Metal Dragoon",
    "Zufällig",
    "Zufällig",
    "Zufällig",
    "Zufällig",
    "Dranzer",
    "Zufällig",
    "Zufällig",
    "Draciel",
    "Dragoon",
    "Driger",
    "Death Driger",
    "Knight Dranzer",
    "Metal Draciel",
    "Kid Dragoon",
    "Dragoon Storm",
    "Dranzer",
    "Galeon",
    "Galzzly",
    "Galman",
    "Wolborg",
    "Seaborg",
    "Draciel",
    "Trygle",
    "Trypio",
    "Driger Slash",
    "Dragoon",
    "Dranzer Spiral",
    "Griffolyon",
    "Master Dragoon",
    "Master Dranzer",
    "Master Draciel",
    "Draciel",
    "Wyborg",
    "Master Driger",
    "Wolborg",
    "Dragoon",
    "Metal Dranzer",
    "Flash Leopard",
    "Driger",
    "Dranzer",
    "Cyber Dragoon",
    "Draciel",
    "-",
    "-",
    "-",
    "-",
    "-",
};

static const unk8* _807C2BC[] = {
    "Ultimate Dragoon",
    "Saizo",
    "Frostic Dranzer",
    "Gekiryu-oh",
    "Megaro Arm",
    "Spark Knight",
    "Polta",
    "Pistol",
    "Ultimate Dragoon",
    "Bakushin-oh",
    "Bump King",
    "Dragoon",
    "Metal Dragoon",
    "Aléatoire",
    "Aléatoire",
    "Aléatoire",
    "Aléatoire",
    "Dranzer",
    "Aléatoire",
    "Aléatoire",
    "Draciel",
    "Dragoon",
    "Driger",
    "Death Driger",
    "Knight Dranzer",
    "Metal Draciel",
    "Kid Dragoon",
    "Dragoon Storm",
    "Dranzer",
    "Galeon",
    "Galzzly",
    "Galman",
    "Wolborg",
    "Seaborg",
    "Draciel",
    "Trygle",
    "Trypio",
    "Driger Slash",
    "Dragoon",
    "Dranzer Spiral",
    "Griffolyon",
    "Master Dragoon",
    "Master Dranzer",
    "Master Draciel",
    "Draciel",
    "Wyborg",
    "Master Driger",
    "Wolborg",
    "Dragoon",
    "Metal Dranzer",
    "Flash Leopard",
    "Driger",
    "Dranzer",
    "Cyber Dragoon",
    "Draciel",
    "-",
    "-",
    "-",
    "-",
    "-",
};

static const unk8* _807C3AC[] = {
    "Ultimate Dragoon",
    "Saizo",
    "Frostic Dranzer",
    "Gekiryu-oh",
    "Megalo Arm",
    "Spark Knight",
    "Polta",
    "Pistol",
    "Ultimate Dragoon",
    "Bakushin-oh",
    "Bump King",
    "Dragoon",
    "Metal Dragoon",
    "Casuale",
    "Casuale",
    "Casuale",
    "Casuale",
    "Dranzer",
    "Casuale",
    "Casuale",
    "Draciel",
    "Dragoon",
    "Driger",
    "Death Driger",
    "Knight Dranzer",
    "Metal Draciel",
    "Kid Dragoon",
    "Attacco tornado",
    "Dranzer",
    "Galeon",
    "Gazzly",
    "Galman",
    "Wolborg",
    "Seaborg",
    "Draciel",
    "Trygle",
    "Trypio",
    "Driger Slash",
    "Dragoon",
    "Dranzer Spiral",
    "Griffol",
    "Master Dragoon",
    "Master Dranzer",
    "Master Draciel",
    "Draciel",
    "Wyborg",
    "Master Driger",
    "Wolborg",
    "Dragoon",
    "Metal Dranzer",
    "Flash Leopard",
    "Driger",
    "Dranzer",
    "Cyber Dragoon",
    "Draciel",
    "-",
    "-",
    "-",
    "-",
    "-",
};

const unk8** _807C49C[] = { _807BFEC, _807C0DC, _807C1CC, _807C2BC, _807C3AC };

static const unk8* _807C4B0[] = {
    "Cross Dragon",
    "Tricutter",
    "Wing Cross",
    "Wing Cross",
    "Cross Dragon",
    "Tricutter",
    "Tricutter",
    "Wing Cross",
    "Cross Dragon",
    "Down Force Ring",
    "Upper Force Ring",
    "Dragon Head",
    "Scissor Cutter",
    "Bound Attack Ring",
    "Bound Defense Ring",
    "Roller Attack Ring",
    "Roller Defense Ring",
    "Wing Cutter",
    "Wing Attack Ring",
    "Wing Defense Ring",
    "Max Shield",
    "Reverse Dragon",
    "Tiger Defender",
    "Star Shape",
    "Knight Crow's Ring",
    "Turtle Survivor",
    "Upper Dragoon",
    "Reverse Dragon",
    "Double Wing",
    "Roaring Lion",
    "Roaring Bear",
    "Roaring Monkey",
    "Reverse Wolf",
    "Whale Attacker",
    "Cross Spike",
    "Triple Wing",
    "Flying Defender",
    "Cross Fang",
    "Dual Dragon",
    "Flame Wing",
    "Cross Griffon",
    "Upper Dragoon",
    "Turtle Survivor",
    "Smash Turtle",
    "Eight Spikes",
    "Double Snake",
    "Knight Crow's Ring",
    "Upper Wolf",
    "Eight Attackers",
    "Scissor Cutter",
    "Panther Claw",
    "Sonic Tiger",
    "Cross Attacker",
    "Cybernetic Dragon",
    "Ten Spike",
    "-",
    "-",
    "-",
    "-",
    "-",
};

static const unk8* _807C5A0[] = {
    "Dragón Cruzado",
    "Tricortador",
    "Ala Cruzada",
    "Ala Cruzada",
    "Dragón Cruzado",
    "Tricortador",
    "Tricortador",
    "Ala Cruzada",
    "Dragón Cruzado",
    "Anillo de Fuerza Gravitatoria",
    "Anillo Antigravitatorio",
    "Cabeza de Dragón",
    "Cortatijeras",
    "Anillo de Ataque Rebote",
    "Anillo de Defensa Rebote",
    "Anillo Rodillo Atacante",
    "Anillo Rodillo Defensivo",
    "Corta Alas",
    "Anillo de Alas de Ataque",
    "Anillo de Alas Defensivas",
    "Escudo Máximo",
    "Dragón Invertido",
    "Defensor Tigre",
    "Forma Estrellada",
    "Anillo Caballero Cuervo",
    "Superviviente Tortuga",
    "Dragón Superior",
    "Dragón Invertido",
    "Ala Doble",
    "León Rugiente",
    "Oso Rugiente",
    "Mono Rugiente",
    "Lobo Invertido",
    "Ballena Ofensiva",
    "Cruz de Pinchos",
    "Ala Triple",
    "Defensor Volante",
    "Colmillo Cruzado",
    "Dragón Dual",
    "Ala Incendiaria",
    "Griffon Cruzado",
    "Dragón Superior",
    "Superviviente Tortuga",
    "Tortuga Aplastante",
    "Ocho Espinas",
    "Serpiente Doble",
    "Anillo Caballero Cuervo",
    "Lobo Superior",
    "Ocho Atacantes",
    "Cortatijeras",
    "Zarpa de Pantera",
    "Tigre Sónico",
    "Ataque Cruzado",
    "Dragón Cibernético",
    "Diez Pinchos",
    "-",
    "-",
    "-",
    "-",
    "-",
};

static const unk8* _807C690[] = {
    "Cross Dragon",
    "Tricutter",
    "Wing Cross",
    "Wing Cross",
    "Cross Dragon",
    "Tricutter",
    "Tricutter",
    "Wing Cross",
    "Cross Dragon",
    "Down Force Ring",
    "Upper Force Ring",
    "Dragon Head",
    "Scissor Cutter",
    "Bound Power-Ring",
    "Bound Abwehr-Ring",
    "Roller Power-Ring",
    "Roller Abwehr-Ring",
    "Wing Cutter",
    "Wing Power-Ring",
    "Wing Abwehr-Ring",
    "Max Shield",
    "Reverse Dragon",
    "Tiger Defender",
    "Star Shape",
    "Knight Crow's Ring",
    "Turtle Survivor",
    "Upper Dragoon",
    "Reverse Dragon",
    "Double Wing",
    "Roaring Lion",
    "Roaring Bear",
    "Roaring Monkey",
    "Reverse Wolf",
    "Whale Attacker",
    "Cross Spike",
    "Triple Wing",
    "Flying Defender",
    "Cross Fang",
    "Dual Dragon",
    "Flame Wing",
    "Cross Griffon",
    "Upper Dragoon",
    "Turtle Survivor",
    "Smash Turtle",
    "Eight Spikes",
    "Double Snake",
    "Knight Crow's Ring",
    "Upper Wolf",
    "Eight Attackers",
    "Scissor Cutter",
    "Panther Claw",
    "Sonic Tiger",
    "Cross Attacker",
    "Cybernetic Dragon",
    "Ten Spike",
    "-",
    "-",
    "-",
    "-",
    "-",
};

static const unk8* _807C780[] = {
    "Cross Dragon",
    "Tricutter",
    "Wing Cross",
    "Wing Cross",
    "Cross Dragon",
    "Tricutter",
    "Tricutter",
    "Wing Cross",
    "Cross Dragon",
    "Anneau force inf.",
    "Anneau force sup.",
    "Tête de dragon",
    "Coupeur ciseaux",
    "Anneau d'attaque bond",
    "Anneau de défense bond",
    "Anneau d'attaque roller",
    "Anneau de défense roller",
    "Wing Cutter",
    "Anneau d'attaque aile",
    "Anneau de défense aile",
    "Bouclier max",
    "Dragon inversé",
    "Défenseur tigre",
    "Forme étoile",
    "Anneau Knight Crow",
    "Tortue Survie",
    "Dragon supérieur",
    "Dragon inversé",
    "Double aile",
    "Lion rugissant",
    "Ours rugissant",
    "Singe hurlant",
    "Loup inversé",
    "Attaqueur baleine",
    "Croix à pointes",
    "Aile triple",
    "Défenseur volant",
    "Croix à crocs",
    "Double dragon",
    "Aile enflammée",
    "Croix griffon",
    "Dragon supérieur",
    "Tortue Survie",
    "Tortue fracassante",
    "Eight Spikes",
    "Double Snake",
    "Anneau Knight Crow",
    "Upper Wolf",
    "Eight Attackers",
    "Coupeur ciseaux",
    "Panther Claw",
    "Sonic Tiger",
    "Cross Attacker",
    "Cybernetic Dragon",
    "Ten Spike",
    "-",
    "-",
    "-",
    "-",
    "-",
};

static const unk8* _807C870[] = {
    "Cross Dragon",
    "Tricutter",
    "Wing Cross",
    "Wing Cross",
    "Cross Dragon",
    "Tricutter",
    "Tricutter",
    "Wing Cross",
    "Cross Dragon",
    "Disco di deportanza",
    "Disco di portanza",
    "Dragon Head",
    "Scissor Cutter",
    "Disco d'attacco compatto",
    "Disco da difesa compatta",
    "Disco d'attacco con rulli",
    "Disco da difesa con rulli",
    "Wing Cutter",
    "Disco d'attacco con le ali",
    "Disco da difesa con le ali",
    "Scudo massimo",
    "Reverse Dragon",
    "Tiger Defender",
    "Forma a stella",
    "Knight Crow's Ring",
    "Turtle Survivor",
    "Upper Dragoon",
    "Reverse Dragon",
    "Doppia ala",
    "Roaring Lion",
    "Roaring Bear",
    "Roaring Monkey",
    "Reverse Wolf",
    "Whale Attacker",
    "Cross Spike",
    "Tripla ala",
    "Flying Defender",
    "Cross Fang",
    "Dual Dragon",
    "Flame Wing",
    "Cross Griffon",
    "Upper Dragoon",
    "Turtle Survivor",
    "Smash Turtle",
    "Eight Spikes",
    "Double Snake",
    "Knight Crow's Ring",
    "Upper Wolf",
    "Eight Attacker",
    "Scissor Cutter",
    "Panther Claw",
    "Sonic Tiger",
    "Cross Attacker",
    "Cybernetic Dragon",
    "Ten Spike",
    "-",
    "-",
    "-",
    "-",
    "-",
};

const unk8** _807C960[] = { _807C4B0, _807C5A0, _807C690, _807C780, _807C870 };

static const unk8* _807C974[] = {
    "Wide",
    "Heavy",
    "Balance",
    "Wide",
    "Heavy",
    "Balance",
    "Wide",
    "Heavy",
    "Balance",
    "Heavy",
    "Wide",
    "Wide",
    "Heavy",
    "Balance",
    "Heavy",
    "Balance",
    "Heavy",
    "Balance",
    "Balance",
    "Heavy",
    "Heavy",
    "Eight Wide",
    "Eight Heavy",
    "Eight Balance",
    "Eight Balance",
    "Eight Heavy",
    "Eight Wide",
    "Eight Wide",
    "Eight Balance",
    "Eight Heavy",
    "Eight Wide",
    "Eight Heavy",
    "Eight Balance",
    "Eight Wide",
    "Eight Balance",
    "Eight Wide",
    "Eight Heavy",
    "Eight Balance",
    "Eight Wide",
    "Eight Heavy",
    "Eight Balance",
    "Eight Heavy",
    "Eight Balance",
    "Eight Wide",
    "Eight Balance",
    "Eight Heavy",
    "Eight Wide",
    "Eight Balance",
    "Ten Wide",
    "Ten Balance",
    "Ten Heavy",
    "Ten Balance",
    "Ten Balance",
    "Ten Wide",
    "Ten Balance",
    "-",
    "-",
    "-",
    "-",
    "-",
};

static const unk8* _807CA64[] = {
    "Ancho",
    "Pesado",
    "Equilibrio",
    "Ancho",
    "Pesado",
    "Equilibrio",
    "Ancho",
    "Pesado",
    "Equilibrio",
    "Pesado",
    "Ancho",
    "Ancho",
    "Pesado",
    "Equilibrio",
    "Pesado",
    "Equilibrio",
    "Pesado",
    "Equilibrio",
    "Equilibrio",
    "Pesado",
    "Pesado",
    "Anchura Ocho",
    "Peso Ocho",
    "Equilibrio Ocho",
    "Equilibrio Ocho",
    "Peso Ocho",
    "Anchura Ocho",
    "Anchura Ocho",
    "Equilibrio Ocho",
    "Peso Ocho",
    "Anchura Ocho",
    "Peso Ocho",
    "Equilibrio Ocho",
    "Anchura Ocho",
    "Equilibrio Ocho",
    "Anchura Ocho",
    "Peso Ocho",
    "Equilibrio Ocho",
    "Anchura Ocho",
    "Peso Ocho",
    "Equilibrio Ocho",
    "Peso Ocho",
    "Equilibrio Ocho",
    "Anchura Ocho",
    "Equilibrio Ocho",
    "Peso Ocho",
    "Anchura Ocho",
    "Equilibrio Ocho",
    "Anchura Diez",
    "Equilibrio Diez",
    "Peso Diez",
    "Equilibrio Diez",
    "Equilibrio Diez",
    "Anchura Diez",
    "Equilibrio Diez",
    "-",
    "-",
    "-",
    "-",
    "-",
};

static const unk8* _807CB54[] = {
    "Breit",
    "Schwer",
    "Ausgleich",
    "Breit",
    "Schwer",
    "Ausgleich",
    "Breit",
    "Schwer",
    "Ausgleich",
    "Schwer",
    "Breit",
    "Breit",
    "Schwer",
    "Ausgleich",
    "Schwer",
    "Ausgleich",
    "Schwer",
    "Ausgleich",
    "Ausgleich",
    "Schwer",
    "Schwer",
    "Eight Wide",
    "Eight Heavy",
    "Eight Balance",
    "Eight Balance",
    "Eight Heavy",
    "Eight Wide",
    "Eight Wide",
    "Eight Balance",
    "Eight Heavy",
    "Eight Wide",
    "Eight Heavy",
    "Eight Balance",
    "Eight Wide",
    "Eight Balance",
    "Eight Wide",
    "Eight Heavy",
    "Eight Balance",
    "Eight Wide",
    "Eight Heavy",
    "Eight Balance",
    "Eight Heavy",
    "Eight Balance",
    "Eight Wide",
    "Eight Balance",
    "Eight Heavy",
    "Eight Wide",
    "Eight Balance",
    "Ten Wide",
    "Ten Balance",
    "Ten Heavy",
    "Ten Balance",
    "Ten Balance",
    "Ten Wide",
    "Ten Balance",
    "-",
    "-",
    "-",
    "-",
    "-",
};

static const unk8* _807CC44[] = {
    "Large",
    "Lourd",
    "Equilibré",
    "Large",
    "Lourd",
    "Equilibré",
    "Large",
    "Lourd",
    "Equilibré",
    "Lourd",
    "Large",
    "Large",
    "Lourd",
    "Equilibré",
    "Lourd",
    "Equilibré",
    "Lourd",
    "Equilibré",
    "Equilibré",
    "Lourd",
    "Lourd",
    "Eight Wide",
    "Eight Heavy",
    "Eight Balance",
    "Eight Balance",
    "Eight Heavy",
    "Eight Wide",
    "Eight Wide",
    "Eight Balance",
    "Eight Heavy",
    "Eight Wide",
    "Eight Heavy",
    "Eight Balance",
    "Eight Wide",
    "Eight Balance",
    "Eight Wide",
    "Eight Heavy",
    "Eight Balance",
    "Eight Wide",
    "Eight Heavy",
    "Eight Balance",
    "Eight Heavy",
    "Eight Balance",
    "Eight Wide",
    "Eight Balance",
    "Eight Heavy",
    "Eight Wide",
    "Eight Balance",
    "Ten Wide",
    "Ten Balance",
    "Ten Heavy",
    "Ten Balance",
    "Ten Balance",
    "Ten Wide",
    "Ten Balance",
    "-",
    "-",
    "-",
    "-",
    "-",
};

static const unk8* _807CD34[] = {
    "Largo",
    "Pesante",
    "Equilibrato",
    "Largo",
    "Pesante",
    "Equilibrato",
    "Largo",
    "Pesante",
    "Equilibrato",
    "Pesante",
    "Largo",
    "Largo",
    "Pesante",
    "Equilibrato",
    "Pesante",
    "Equilibrato",
    "Pesante",
    "Equilibrato",
    "Equilibrato",
    "Pesante",
    "Pesante",
    "Eight largo",
    "Eight pesante",
    "Eight equilibrato",
    "Eight equilibrato",
    "Eight pesante",
    "Eight largo",
    "Eight largo",
    "Eight equilibrato",
    "Eight pesante",
    "Eight largo",
    "Eight pesante",
    "Eight equilibrato",
    "Eight largo",
    "Eight equilibrato",
    "Eight largo",
    "Eight pesante",
    "Eight equilibrato",
    "Eight largo",
    "Eight pesante",
    "Eight equilibrato",
    "Eight pesante",
    "Eight equilibrato",
    "Eight largo",
    "Eight equilibrato",
    "Eight pesante",
    "Eight largo",
    "Eight equilibrato",
    "Ten largo",
    "Ten equilibrato",
    "Ten pesante",
    "Ten equilibrato",
    "Ten equilibrato",
    "Ten largo",
    "Ten equilibrato",
    "-",
    "-",
    "-",
    "-",
    "-",
};

const unk8** _807CE24[] = { _807C974, _807CA64, _807CB54, _807CC44, _807CD34 };

static const unk8* _807CE38[] = {
    "Flat",
    "Sharp",
    "Semi-Flat",
    "Semi-Flat",
    "Flat",
    "Sharp",
    "Sharp",
    "Semi-Flat",
    "Flat",
    "Flat",
    "Semi-Flat",
    "Grip",
    "Bearing",
    "Flat",
    "Sharp",
    "Flat",
    "Semi-Flat",
    "Auto-Change",
    "Semi-Flat",
    "Semi-Flat",
    "Metal Ball",
    "Storm Grip",
    "Metal Change",
    "SG Sharp",
    "SG Semi-Flat",
    "Metal Sting",
    "SG Flat",
    "Storm Grip",
    "Spiral Change",
    "SG Semi-Flat",
    "SG Flat",
    "SG Sharp",
    "SG Bearing",
    "Defense Grip",
    "SG Metal Ball",
    "SG Jumping",
    "SG Sharp",
    "Full Auto-Clutch",
    "Phantom Grip",
    "Flame Change",
    "Griffolyon Base",
    "SG Flat",
    "Metal Sting",
    "SG Sharp",
    "Fortress",
    "SG Auto-Change",
    "SG Semi-Flat",
    "Defense Grip 2",
    "Magne Flat",
    "SG Flat",
    "SG Semi-Flat",
    "SG Metal Flat",
    "Volcano Change",
    "Jumping Base 2",
    "Viper Metal Ball",
    "-",
    "-",
    "-",
    "-",
    "-",
};

static const unk8* _807CF28[] = {
    "Plano",
    "Afilado",
    "Semi Plano",
    "Semi Plano",
    "Plano",
    "Afilado",
    "Afilado",
    "Semi Plano",
    "Plano",
    "Plano",
    "Semi Plano",
    "Agarre",
    "Engranaje",
    "Plano",
    "Afilado",
    "Plano",
    "Semi Plano",
    "Autocambio",
    "Semi Plano",
    "Semi Plano",
    "Bola de Metal",
    "Agarre Tormenta",
    "Cambio de Metal",
    "ER Afilado",
    "ER Semi-Plano",
    "Aguijón Metálico",
    "ER Plano",
    "Agarre Tormenta",
    "Cambio Espiral",
    "ER Semi-Plano",
    "ER Plano",
    "ER Afilado",
    "Engranaje ER",
    "Agarre Defensivo",
    "ER Bola Metálica",
    "ER Saltarín",
    "ER Afilado",
    "Autoagarre Total",
    "Agarre Fantasma",
    "Cambio de Llama",
    "Base Griffolyon",
    "ER Plano",
    "Aguijón Metálico",
    "ER Afilado",
    "Fortaleza",
    "ER Autocambio",
    "ER Semi-Plano",
    "Agarre Defensivo 2",
    "Plano Magnético",
    "ER Plano",
    "ER Semi-Plano",
    "ER Metal Plano",
    "Cambio Volcán",
    "Base Saltarina 2",
    "Bola Metálica Cobra",
    "-",
    "-",
    "-",
    "-",
    "-",
};

static const unk8* _807D018[] = {
    "Flach",
    "Spitz",
    "Mittel",
    "Mittel",
    "Flach",
    "Spitz",
    "Spitz",
    "Mittel",
    "Flach",
    "Flach",
    "Mittel",
    "Grip",
    "Bearing",
    "Flach",
    "Spitz",
    "Flach",
    "Mittel",
    "Auto-Change",
    "Mittel",
    "Mittel",
    "Metal Ball",
    "Storm Grip",
    "Metal Change",
    "SG Sharp",
    "SG Semi-Flat",
    "Metal Sting",
    "SG Flat",
    "Storm Grip",
    "Spiral Change",
    "SG Semi-Flat",
    "SG Flat",
    "SG Sharp",
    "SG Bearing",
    "Defense Grip",
    "SG Metal Ball",
    "SG Jumping",
    "SG Sharp",
    "Full Auto-Clutch",
    "Phantom Grip",
    "Flame Change",
    "Griffolyon Base",
    "SG Flat",
    "Metal Sting",
    "SG Sharp",
    "Fortress",
    "SG Auto-Change",
    "SG Semi-Flat",
    "Defense Grip 2",
    "Magne Flach",
    "SG Flat",
    "SG Semi-Flat",
    "SG Metal Flat",
    "Volcano Change",
    "Jumping Base 2",
    "Viper Metal Ball",
    "-",
    "-",
    "-",
    "-",
    "-",
};

static const unk8* _807D108[] = {
    "Flat",
    "Sharp",
    "Semi-Flat",
    "Semi-Flat",
    "Flat",
    "Sharp",
    "Sharp",
    "Semi-Flat",
    "Flat",
    "Flat",
    "Semi-Flat",
    "Prise",
    "Support",
    "Flat",
    "Sharp",
    "Flat",
    "Semi-Flat",
    "Auto-Change",
    "Semi-Flat",
    "Semi-Flat",
    "Metal Ball",
    "Storm Grip",
    "Metal Change",
    "SG Sharp",
    "SG Semi-Flat",
    "Metal Sting",
    "SG Flat",
    "Storm Grip",
    "Spiral Change",
    "SG Semi-Flat",
    "SG Flat",
    "SG Sharp",
    "SG Bearing",
    "Defense Grip",
    "SG Metal Ball",
    "SG Jumping",
    "SG Sharp",
    "Full Auto-Clutch",
    "Phantom Grip",
    "Flame Change",
    "Base Griffolyon",
    "SG Flat",
    "Metal Sting",
    "SG Sharp",
    "Fortress",
    "SG Auto-Change",
    "SG Semi-Flat",
    "Defense Grip 2",
    "Magne Flat",
    "SG Flat",
    "SG Semi-Flat",
    "SG Metal Flat",
    "Volcano Change",
    "Jumping Base 2",
    "Viper Metal Ball",
    "-",
    "-",
    "-",
    "-",
    "-",
};

static const unk8* _807D1F8[] = {
    "Piatta",
    "Acuta",
    "Semipiatta",
    "Semipiatta",
    "Piatta",
    "Acuta",
    "Acuta",
    "Semipiatta",
    "Piatta",
    "Piatta",
    "Semipiatta",
    "Aderenza",
    "Portante",
    "Piatta",
    "Acuta",
    "Piatta",
    "Semipiatta",
    "Automodificante",
    "Semipiatta",
    "Semipiatta",
    "Sfera metallica",
    "Storm Grip",
    "Metallica mobile",
    "MR acuta",
    "MR semipiatta",
    "Pungiglione metallico",
    "MR piatta",
    "Storm Grip",
    "Spirale mobile",
    "MR semipiatta",
    "MR piatta",
    "MR acuta",
    "MR portante",
    "Difesa aderenza",
    "MR sfera metallica",
    "MR salto",
    "MR acuta",
    "Frizione automatica",
    "Phantom Grip",
    "Flame Change",
    "Base del Griffol",
    "MR piatta",
    "Pungiglione metallico",
    "MR acuta",
    "Fortezza",
    "MR automodificante",
    "MR semipiatta",
    "Difesa aderenza 2",
    "Magnetica piatta",
    "MR piatta",
    "MR semipiatta",
    "MR metallica piatta",
    "Vulcanica mobile",
    "Base di salto 2",
    "Vipera sfera metallica",
    "-",
    "-",
    "-",
    "-",
    "-",
};

const unk8** _807D2E8[] = { _807CE38, _807CF28, _807D018, _807D108, _807D1F8 };

const unk8* _807D2FC[] = {
    "None",
    "None",
    "None",
    "None",
    "None",
    "None",
    "None",
    "None",
    "None",
    "None",
    "None",
    "None",
    "None",
    "None",
    "None",
    "None",
    "None",
    "None",
    "None",
    "None",
    "None",
    "Left Spin Gear",
    "Right Spin Gear",
    "Right Spin Gear",
    "Right Spin Gear",
    "Right Spin Gear",
    "Right Spin Gear",
    "Left Spin Gear",
    "Right Spin Gear",
    "Right Spin Gear",
    "Right Spin Gear",
    "Right Spin Gear",
    "Right Spin Gear",
    "Right Spin Gear",
    "Right Spin Gear",
    "Right Spin Gear",
    "Right Spin Gear",
    "Right Spin Gear",
    "Left Spin Gear",
    "Right Spin Gear",
    "None",
    "Right Spin Gear",
    "Right Spin Gear",
    "Right Spin Gear",
    "Right Spin Gear",
    "Right Spin Gear",
    "Right Spin Gear",
    "Right Spin Gear",
    "NEO Left Spin Gear",
    "NEO Right Spin Gear",
    "NEO Right Spin Gear",
    "NEO Right Spin Gear",
    "NEO Right Spin Gear",
    "Right Spin Gear",
    "NEO Right Spin Gear",
    "-",
    "-",
    "-",
    "-",
    "-",
};

const unk8* _807D3EC[] = {
    "Ninguno",
    "Ninguno",
    "Ninguno",
    "Ninguno",
    "Ninguno",
    "Ninguno",
    "Ninguno",
    "Ninguno",
    "Ninguno",
    "Ninguno",
    "Ninguno",
    "Ninguno",
    "Ninguno",
    "Ninguno",
    "Ninguno",
    "Ninguno",
    "Ninguno",
    "Ninguno",
    "Ninguno",
    "Ninguno",
    "Ninguno",
    "Engranaje Rotación Izquierda",
    "Engranaje Rotación Derecha",
    "Engranaje Rotación Derecha",
    "Engranaje Rotación Derecha",
    "Engranaje Rotación Derecha",
    "Engranaje Rotación Derecha",
    "Engranaje Rotación Izquierda",
    "Engranaje Rotación Derecha",
    "Engranaje Rotación Derecha",
    "Engranaje Rotación Derecha",
    "Engranaje Rotación Derecha",
    "Engranaje Rotación Derecha",
    "Engranaje Rotación Derecha",
    "Engranaje Rotación Derecha",
    "Engranaje Rotación Derecha",
    "Engranaje Rotación Derecha",
    "Engranaje Rotación Derecha",
    "Engranaje Rotación Izquierda",
    "Engranaje Rotación Derecha",
    "Ninguno",
    "Engranaje Rotación Derecha",
    "Engranaje Rotación Derecha",
    "Engranaje Rotación Derecha",
    "Engranaje Rotación Derecha",
    "Engranaje Rotación Derecha",
    "Engranaje Rotación Derecha",
    "Engranaje Rotación Derecha",
    "Engranaje Rotación Izquierda NEO",
    "Engranaje Rotación Derecha NEO",
    "Engranaje Rotación Derecha NEO",
    "Engranaje Rotación Derecha NEO",
    "Engranaje Rotación Derecha NEO",
    "Engranaje Rotación Derecha",
    "Engranaje Rotación Derecha NEO",
    "-",
    "-",
    "-",
    "-",
    "-",
};

const unk8* _807D4DC[] = {
    "Nicht vorhanden",
    "Nicht vorhanden",
    "Nicht vorhanden",
    "Nicht vorhanden",
    "Nicht vorhanden",
    "Nicht vorhanden",
    "Nicht vorhanden",
    "Nicht vorhanden",
    "Nicht vorhanden",
    "Nicht vorhanden",
    "Nicht vorhanden",
    "Nicht vorhanden",
    "Nicht vorhanden",
    "Nicht vorhanden",
    "Nicht vorhanden",
    "Nicht vorhanden",
    "Nicht vorhanden",
    "Nicht vorhanden",
    "Nicht vorhanden",
    "Nicht vorhanden",
    "Nicht vorhanden",
    "Linksdr. Kreiselscheibe",
    "Rechtsdr. Kreiselscheibe",
    "Rechtsdr. Kreiselscheibe",
    "Rechtsdr. Kreiselscheibe",
    "Rechtsdr. Kreiselscheibe",
    "Rechtsdr. Kreiselscheibe",
    "Linksdr. Kreiselscheibe",
    "Rechtsdr. Kreiselscheibe",
    "Rechtsdr. Kreiselscheibe",
    "Rechtsdr. Kreiselscheibe",
    "Rechtsdr. Kreiselscheibe",
    "Rechtsdr. Kreiselscheibe",
    "Rechtsdr. Kreiselscheibe",
    "Rechtsdr. Kreiselscheibe",
    "Rechtsdr. Kreiselscheibe",
    "Rechtsdr. Kreiselscheibe",
    "Rechtsdr. Kreiselscheibe",
    "Linksdr. Kreiselscheibe",
    "Rechtsdr. Kreiselscheibe",
    "Nicht vorhanden",
    "Rechtsdr. Kreiselscheibe",
    "Rechtsdr. Kreiselscheibe",
    "Rechtsdr. Kreiselscheibe",
    "Rechtsdr. Kreiselscheibe",
    "Rechtsdr. Kreiselscheibe",
    "Rechtsdr. Kreiselscheibe",
    "Rechtsdr. Kreiselscheibe",
    "NEO linksdr. Kreiselscheibe",
    "NEO rechtsdr. Kreiselscheibe",
    "NEO rechtsdr. Kreiselscheibe",
    "NEO rechtsdr. Kreiselscheibe",
    "NEO rechtsdr. Kreiselscheibe",
    "Rechtsdr. Kreiselscheibe",
    "NEO rechtsdr. Kreiselscheibe",
    "-",
    "-",
    "-",
    "-",
    "-",
};

const unk8* _807D5CC[] = {
    "Aucun",
    "Aucun",
    "Aucun",
    "Aucun",
    "Aucun",
    "Aucun",
    "Aucun",
    "Aucun",
    "Aucun",
    "Aucun",
    "Aucun",
    "Aucun",
    "Aucun",
    "Aucun",
    "Aucun",
    "Aucun",
    "Aucun",
    "Aucun",
    "Aucun",
    "Aucun",
    "Aucun",
    "Engrenages gauches",
    "Engrenages droits",
    "Engrenages droits",
    "Engrenages droits",
    "Engrenages droits",
    "Engrenages droits",
    "Engrenages gauches",
    "Engrenages droits",
    "Engrenages droits",
    "Engrenages droits",
    "Engrenages droits",
    "Engrenages droits",
    "Engrenages droits",
    "Engrenages droits",
    "Engrenages droits",
    "Engrenages droits",
    "Engrenages droits",
    "Engrenages gauches",
    "Engrenages droits",
    "Aucun",
    "Engrenages droits",
    "Engrenages droits",
    "Engrenages droits",
    "Engrenages droits",
    "Engrenages droits",
    "Engrenages droits",
    "Engrenages droits",
    "Engrenages gauches NEO",
    "Engrenages droits NEO",
    "Engrenages droits NEO",
    "Engrenages droits NEO",
    "Engrenages droits NEO",
    "Engrenages droits",
    "Engrenages droits NEO",
    "-",
    "-",
    "-",
    "-",
    "-",
};

const unk8* _807D6BC[] = {
    "Assente",
    "Assente",
    "Assente",
    "Assente",
    "Assente",
    "Assente",
    "Assente",
    "Assente",
    "Assente",
    "Assente",
    "Assente",
    "Assente",
    "Assente",
    "Assente",
    "Assente",
    "Assente",
    "Assente",
    "Assente",
    "Assente",
    "Assente",
    "Assente",
    "Meccanismo di rotazione sx",
    "Meccanismo di rotazione dx",
    "Meccanismo di rotazione dx",
    "Meccanismo di rotazione dx",
    "Meccanismo di rotazione dx",
    "Meccanismo di rotazione dx",
    "Meccanismo di rotazione sx",
    "Meccanismo di rotazione dx",
    "Meccanismo di rotazione dx",
    "Meccanismo di rotazione dx",
    "Meccanismo di rotazione dx",
    "Meccanismo di rotazione dx",
    "Meccanismo di rotazione dx",
    "Meccanismo di rotazione dx",
    "Meccanismo di rotazione dx",
    "Meccanismo di rotazione dx",
    "Meccanismo di rotazione dx",
    "Meccanismo di rotazione sx",
    "Meccanismo di rotazione dx",
    "Assente",
    "Meccanismo di rotazione dx",
    "Meccanismo di rotazione dx",
    "Meccanismo di rotazione dx",
    "Meccanismo di rotazione dx",
    "Meccanismo di rotazione dx",
    "Meccanismo di rotazione dx",
    "Meccanismo di rotazione dx",
    "NEO meccan. di rotaz. sx",
    "NEO meccan. di rotaz. dx",
    "NEO meccan. di rotaz. dx",
    "NEO meccan. di rotaz. dx",
    "NEO meccan. di rotaz. dx",
    "Meccanismo di rotazione dx",
    "NEO meccan. di rotaz. dx",
    "-",
    "-",
    "-",
    "-",
    "-",
};

const unk8** _807D7AC[] = { _807D2FC, _807D3EC, _807D4DC, _807D5CC, _807D6BC };

unk8 byte_807D7C0[]
    = { 0, 1, 2, 3, 0, 1, 2, 3, 0, 1, 0, 1, 2, 3, 0, 1, 2, 3, 0, 1, 0, 1, 1, 3, 0, 1, 2, 2, 3, 1, 0,
          1, 2, 3, 0, 1, 2, 1, 2, 3, 0, 1, 2, 3, 0, 1, 2, 3, 0, 1, 0, 1, 2, 3, 0, 1, 2, 3, 0, 1 };

const BeybladeData* getBeybladeData0(unk32 arg0)
{
    return &_807ac28[arg0];
}

BeybladeActorData* getBeybladeActorData(unk32 arg0)
{
    BeybladeActorData* data;

    data = _gameData->actorData.records;
    return &data[arg0];
}

void allocateBeyBladeActorPalette(unk32 arg0, unk32 arg1)
{
    CopyFn** copy;
    void* destination;
    const void* source;

    getBeybladeData0(arg0);
    source = RiderPalettes[arg0];
    copy = &__fastMemoryCopyARM;
    arg1 <<= 5;
    destination = (void*)OBJ_PLTT;
    destination += arg1;
    (*copy)(source, destination, 0x20);
}

void allocateBeybladeObjectPalettes(void)
{
    BeybladeActorData* records;
    s32 index;

    records = _gameData->actorData.records;
    for (index = 0; index <= 0x3B; index++) {
        if (records->block != NULL) {
            allocateBeyBladeActorPalette(index, records->unk4);
        }
        records++;
    }
}

const unk8* sub_80573C8(unk32 arg0)
{
    return _807b858[arg0];
}

const unk8* sub_80573DC(unk32 arg0)
{
    return _807BFD8[getLanguageTextIndex()][arg0];
}

const unk8* sub_80573FC(unk32 arg0)
{
    return _807C49C[getLanguageTextIndex()][arg0];
}

const unk8* sub_805741C(unk32 arg0)
{
    return _807C960[getLanguageTextIndex()][arg0];
}

const unk8* sub_805743C(unk32 arg0)
{
    return _807CE24[getLanguageTextIndex()][arg0];
}

const unk8* sub_805745C(unk32 arg0)
{
    return _807D2E8[getLanguageTextIndex()][arg0];
}

const unk8* sub_805747C(unk32 arg0)
{
    return _807D7AC[getLanguageTextIndex()][arg0];
}

unk8 sub_805749C(unk32 arg0)
{
    return byte_807D7C0[arg0];
}
