on:
  push:
  pull_request:

jobs:
  clang-format:
    runs-on: ubuntu-latest
    steps:
      - run: sudo apt-get install colordiff -y
      - uses: actions/checkout@v2
      - run: ./scripts/run-clang-format.py -r src | colordiff

  build:
    runs-on: ubuntu-latest
    container: devkitpro/devkitarm

    steps:
      - uses: actions/checkout@v2

      - name: "Install tools"
        run: |
          sudo apt-get update
          sudo apt-get install build-essential gcc libpng-dev -y

      - run: |
          sudo apt-get install software-properties-common -y
          sudo apt-add-repository 'deb http://deb.debian.org/debian stretch-backports main'
          sudo apt-add-repository 'deb http://deb.debian.org/debian stretch-backports-sloppy main'
          sudo apt update
          sudo apt -t stretch-backports-sloppy install libarchive13 -y
          sudo apt -t stretch-backports install cmake nodejs -y
        shell: bash
      - run: cmake --version

      - uses: actions/checkout@v2
        with:
          repository: pret/agbcc
          path: agbcc
      - run: ./build.sh
        working-directory: agbcc

      - name: Create Build Environment
        run: mkdir build

      - name: Configure CMake
        run: cmake ..
        working-directory: ${{ github.workspace }}/build
        env:
          AGBCC: ${{ github.workspace }}/agbcc

      - run: make
        working-directory: ${{ github.workspace }}/build

      - run: make compare
        working-directory: ${{ github.workspace }}/build
